apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route1
spec:
  http:
    - name: route-1
      match:
        hosts:
          - acitrus.cn
        paths:
          - /*

      backends:
        - serviceName: api-gateway
          servicePort: 9443
#      plugins:
#        - name: proxy-rewrite
#          enable: true
#          config:
#            uri: /*
