FROM orientdb:3.2.22 as db

FROM wfybelief/jdk-8:dev as java


# https://orientdb.com/docs/3.2.x/programs/server.html
ENV ORIENTDB_HOME=/orientdb \
    ORIENTDB_OPTS_MEMORY="\
        -XX:InitialRAMPercentage=35.0 \
        -XX:MaxRAMPercentage=35.0 \
        -Xshareclasses \
        -Xtune:virtualized \
        -Xquickstart \
        -XX:+UseContainerSupport" \
    PATH=/orientdb/bin:$PATH

COPY --from=db /orientdb /orientdb

WORKDIR /orientdb

# <!-- TODO: Use K8s hazelcast plugin: https://github.com/orientechnologies/orientdb-docker  -->
VOLUME ["/orientdb/backup", "/orientdb/databases", "/orientdb/config"]

# http://orientdb.org/enterprise-agent-open-source
# https://jar-download.com/?search_box=com.orientechnologies.agent

ADD orientdb-enterprise-agent/agent/target/agent-3.2.22.jar /orientdb/plugins/

ENTRYPOINT ["server.sh"]
CMD []