export const catalogue = {
  services: [
    { id: "traefik", name: "Traefik", href: "https://traefik.acitrus.cn", landmark: "ingress" },
    { id: "authelia", name: "Authelia", href: "https://auth.acitrus.cn", landmark: "identity" },
    { id: "claude-code-hub", name: "Claude Code Hub", href: "https://inner.coding.acitrus.cn", landmark: "application" },
    { id: "rustfs", name: "RustFS", href: "https://s3.acitrus.cn", landmark: "storage" },
    { id: "lldap", name: "LLDAP", href: "https://ldap.acitrus.cn", landmark: "directory" },
    { id: "postgresql", name: "PostgreSQL", landmark: "database" },
    { id: "redis", name: "Redis", landmark: "cache" },
  ],
  relations: [
    { source: "traefik", target: "authelia", type: "route" },
    { source: "traefik", target: "claude-code-hub", type: "route" },
    { source: "traefik", target: "rustfs", type: "route" },
    { source: "traefik", target: "lldap", type: "route" },
    { source: "claude-code-hub", target: "authelia", type: "authentication" },
    { source: "rustfs", target: "authelia", type: "authentication" },
    { source: "authelia", target: "lldap", type: "authentication" },
    { source: "claude-code-hub", target: "postgresql", type: "data" },
    { source: "authelia", target: "postgresql", type: "data" },
    { source: "lldap", target: "postgresql", type: "data" },
    { source: "claude-code-hub", target: "redis", type: "cache" },
    { source: "authelia", target: "redis", type: "cache" },
  ],
};
