apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      name: httpbin
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http.acitrus.cn
  namespace: default
  labels:
    app.kubernetes.io/name: httpbin
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # https://doc.traefik.io/traefik/middlewares/overview/
    - kind: Rule
      match: Host(`http.acitrus.cn`)
      services:
        - kind: Service
          name: httpbin
          port: 80
      middlewares:
        - name: http-to-https
        - name: 'forwardauth-authelia' # name of your middleware, as defined in your middleware.yml
          namespace: 'default'