image:
  registry: docker.io

ingress:
  enabled: true
  traefikCRD:
    enabled: true
    entryPoints:
      - web
      - websecure

pod:
  # Must be Deployment, DaemonSet, or StatefulSet.
  kind: 'Deployment'

configMap:

  log:
    ## Level of verbosity for logs: info, debug, trace.
    level: 'trace'

  authentication_backend:
    ldap:

      ## Enable LDAP Backend.
      enabled: true

      ## The LDAP implementation, this affects elements like the attribute utilised for resetting a password.
      ## Acceptable options are as follows:
      ## - 'activedirectory' - For Microsoft Active Directory.
      ## - 'custom' - For custom specifications of attributes and filters.
      ## This currently defaults to 'custom' to maintain existing behaviour.
      ##
      ## Depending on the option here certain other values in this section have a default value, notably all of the
      ## attribute mappings have a default value that this config overrides, you can read more about these default values
      ## at https://www.authelia.com/reference/guides/ldap/#defaults
      implementation: 'lldap'

      ## The address for the ldap server. Format: <scheme>://<address>[:<port>].
      ## Scheme can be ldap or ldaps in the format (port optional).
      address: 'ldap://iam-ldap.default:3890'

      ## Connection Timeout.
      timeout: '5 seconds'

      ## Use StartTLS with the LDAP connection.
      start_tls: false

      ## The base dn for every LDAP query.
      base_dn: 'DC=acitrus,DC=cn'

      ## An additional dn to define the scope to all users.
      additional_users_dn: 'OU=people'

      ## The users filter used in search queries to find the user profile based on input filled in login form.
      ## Various placeholders are available in the user filter:
      ## - {input} is a placeholder replaced by what the user inputs in the login form.
      ## - {username_attribute} is a mandatory placeholder replaced by what is configured in `username_attribute`.
      ## - {mail_attribute} is a placeholder replaced by what is configured in `mail_attribute`.
      ## - DON'T USE - {0} is an alias for {input} supported for backward compatibility but it will be deprecated in later
      ##   versions, so please don't use it.
      ##
      ## Recommended settings are as follows:
      ## - Microsoft Active Directory: (&({username_attribute}={input})(objectCategory=person)(objectClass=user))
      ## - OpenLDAP:
      ##   - (&({username_attribute}={input})(objectClass=person))
      ##   - (&({username_attribute}={input})(objectClass=inetOrgPerson))
      ##
      ## To allow sign in both with username and email, one can use a filter like
      ## (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
      users_filter: '(&({username_attribute}={input})(objectClass=person))'

      ## An additional dn to define the scope of groups.
      additional_groups_dn: 'OU=groups'

      ## The groups filter used in search queries to find the groups of the user.
      ## - {input} is a placeholder replaced by what the user inputs in the login form.
      ## - {username} is a placeholder replace by the username stored in LDAP (based on `username_attribute`).
      ## - {dn} is a matcher replaced by the user distinguished name, aka, user DN.
      ## - {username_attribute} is a placeholder replaced by what is configured in `username_attribute`.
      ## - {mail_attribute} is a placeholder replaced by what is configured in `mail_attribute`.
      ## - DON'T USE - {0} is an alias for {input} supported for backward compatibility but it will be deprecated in later
      ##   versions, so please don't use it.
      ## - DON'T USE - {1} is an alias for {username} supported for backward compatibility but it will be deprecated in
      ##   later version, so please don't use it.
      ##
      ## If your groups use the `groupOfUniqueNames` structure use this instead:
      ##    (&(uniquemember={dn})(objectclass=groupOfUniqueNames))
      groups_filter: '(member={dn})'

      ## The username of the admin user.
      user: 'uid=reader,ou=people,dc=acitrus,dc=cn'

      password:
        ## Disables this secret and leaves configuring it entirely up to you.
        disabled: false

        ## The secret name. The ~ name is special as it is the secret we generate either automatically or via the
        ## secret_value option below.
        secret_name: ~

        ## The value of a generated secret when using the ~ secret_name.
        value: 'qQKMdVrLmbuYXu1eGxTC'

        ## The path to the secret. If it has a '/' prefix it's assumed to be an absolute path within the pod. Otherwise
        ## it uses the format '{mountPath}/{secret_name}/{path}' where '{mountPath}' refers to the 'secret.mountPath'
        ## value, '{secret_name}' is the secret_name above, and '{path}' is this value.
        path: 'authentication.ldap.password.txt'

      attributes:
        distinguished_name: 'distinguishedName'
        username: 'uid'
        mail: 'mail'
        member_of: 'memberOf'
        group_name: 'cn'

  session:
    redis:
      enabled: true
      enabledSecret: true
      host: 'redis-master.default'
      port: 6379

    encryption_key:
      ## The value of a generated secret when using the ~ secret_name.
      value: 'X6awd^.ZGwcfEacfcGy!HQ!)H043T2CbqG3kVH]C!#.0%>F8bM>Z@rGQg,tce2rKp~j-5knK=)F~}t4H+zZqQ?x}Qnn!aMan^q6>'

    cookies:
      - domain: 'acitrus.cn'
        subdomain: 'auth'
        authelia_url: 'https://auth.acitrus.cn'
        name: 'authelia_session'
        # same_site: 'lax'
        # inactivity: '5m'
        # expiration: '1h'
        # remember_me: '1d'

  storage:
    encryption_key:
      value: 'J~d_+Pyxy!e4e:Q-)W8pe0D8.@^*qD2^sh1ZczE>N-wns7WP-]tWk27P.RmLNwjtPLW2y9,KDv3Ump50PGsdsW>~Qwq=Y5Fa)ru*'

  notifier:
    filesystem:
      enabled: true
      filename: '/config/notification.txt'

  access_control:
    secret:
      enabled: true

    # It must be either 'bypass', 'one_factor', 'two_factor' or 'deny'.
    rules:
      #      - domain: 'http.acitrus.cn'
      #        policy: 'bypass'
      #        methods:
      #          - 'GET'
      #
      #      - domain: 'http.acitrus.cn'
      #        subject:
      #          - 'group:public_read_write'
      #        policy: 'one_factor'

      # nacos
      - domain: 'nacos.acitrus.cn'
        policy: 'bypass'
        methods:
          - 'GET'
      - domain: 'nacos.acitrus.cn'
        subject:
          - 'group:public_read_write'
        policy: 'one_factor'
      # home
      - domain: 'home.acitrus.cn'
        subject:
          - 'group:public_readonly'
        policy: 'one_factor'
        methods:
          - 'GET'
      - domain: 'home.acitrus.cn'
        subject:
          - 'group:public_read_write'
        policy: 'one_factor'

  identity_providers:
    oidc:
      ## Enables this in the config map. Currently in beta stage.
      ## See https://www.authelia.com/r/openid-connect/
      enabled: true
      jwks:
        - key_id: ''
          use: 'sig'
          key:
            value: |
              -----BEGIN PRIVATE KEY-----
              MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClUDFLPoUl4i0z
              kPPNQGf7xUNiQ/+YZ9z7TX7LBpEoCwvfYIIm8w6ZkswaYYY4KYlnqBsnMx5Y6ZpL
              QhuLWjD48pxKWp15TqjdgLmbA3orHRR6pZT0I6y9qr2Xs4IafEZcJ0BUR8T158io
              hzMNnvDmtpGmhXXPI/ViZS7dIYLfGhay4YVRWniooHIuAHQNAO8bqIJYiLtkXj56
              B8/n+C+TInSjnU77KosPfxGrlDdtTzn6qh69JTlXCyfd1nQWVSYJphlHzfRoYOaS
              vG3ecGfCLezKcI6tzfucehSXkLyTn1XteeBeQMW4od+UcG2ckXrj2Od9TTbd7yDl
              Nn305itjAgMBAAECggEAKNwZ2v3Afj0ZrAmzYPN+4BmBTrv85GgjlA+y+66LWUjl
              rdgWQ1dHMAk7HnglayNFHZRM5dL6OMLAisJzuW1Y9mdM3wnnq1CYZ2tGNPzWiOp+
              odPkbbWVoCmgA+twCGjYITXobgxxL9CS5ajJIyA6beQJOw34sPKz15anzytVxBuy
              dt5jXfxgaIJDY6TXwXfn0o5RjFXi+ioKDIfHQjG4nWuvdORHOKoqmRO1hq4RSlbm
              5841uYIKYUraVSbXX05J8UC5+FtnMtSRpJVQMAfwDIhbJaesFgm3phLksWp7WJfK
              1Z3Yrxs2TnpE/seeYdK0k8Ts4iThJW8Ee3hB4so6UQKBgQDPYS7mG/BT8aBpGtQg
              kgnxQvKWN4kwRwRiik2Ok3irCW7rvNuL6pa51bWMUaJapReoVuIlDkt9EuyefLyn
              8R6c+AK4jcRnEW6ZcfLs/zziYTu2YW5wpSoYsDRbQmhShChjDP+vOIWTlpyYybZ4
              k1VgxCAhpYXP9rIq1esxPlyGMwKBgQDMEjUwtaTVPx/l1WZaEM6nxWFUhvlf/COH
              nQtLDs2XmF7Z8VeAoDynify/arAEDGZsdzRPkOfht1WMU6ALJz/K6EzjJbgrO6gi
              Q/GT8Rjj3vHKeBqYA1lWGO8A6WNZ1iQ/dtM+DVLeF6z9AKfPy4blTr0Jl98efBW6
              rz/2bkO2EQKBgGeRZ3SwW1PxBmW3al1h0elVwAVZcwBTV1NHMviTmd4Bdg3xYcv8
              uo3Qtzx+wJB4htohmgtbmkO6ocV9ElLlTp6iFenJk17OC+hCSkomJmgAm2u4OQm0
              0tNFnMA+6A7dxbXCFieSGNPekhKUGrcZDbin+kwTeEKmN9DAyRbsyBSVAoGABpxU
              YsaPl2TbGKvoC+TdfOvU8lMJAwX89Kius/i/yjhiYjcCOaV3MYozyNOg7hCkxMC7
              zhQInvQ8bjZLSfE0jNMnongXVjcxhCKlUcCOqNsRBBkN63y4SSS3oVTuJfvc4r1r
              rGfsFku4C94YkY+rSARb9VKZJLiqT4jbzpTV1rECgYEAj8eV+pnbDr+vmemxSo3T
              hBcsKeL/hd3l2I73IFZGWRUEjSCii5arEv8upShBuMMGMmDG8bNzUeDn3Wb96QuN
              aVN7R/R57QMbYpA1giIS/C59Y+zJL2Sf1Y52SZdrYL2F+/E5Ae985/Lwt+1EWNGh
              L9CTmFsn4TyhOwzc2VdjIY4=
              -----END PRIVATE KEY-----

      clients:
        - client_id: 'unique-client-identifier'
          client_name: 'My Application'
          client_secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'  # The digest of 'insecure_secret'.
          redirect_uris:
            - 'https://oidc.acitrus.cn:8080/oauth2/callback'
          audience:
            - 'https://app.acitrus.cn'