image:
  registry: docker.io

ingress:
  enabled: true
  traefikCRD:
    enabled: true
    entryPoints:
      - web
      - websecure

pod:
  # Must be Deployment, DaemonSet, or StatefulSet.
  kind: 'Deployment'

configMap:

  log:
    ## Level of verbosity for logs: info, debug, trace.
    level: 'info'

  authentication_backend:
    ldap:

      ## Enable LDAP Backend.
      enabled: true

      ## The LDAP implementation, this affects elements like the attribute utilised for resetting a password.
      ## Acceptable options are as follows:
      ## - 'activedirectory' - For Microsoft Active Directory.
      ## - 'custom' - For custom specifications of attributes and filters.
      ## This currently defaults to 'custom' to maintain existing behaviour.
      ##
      ## Depending on the option here certain other values in this section have a default value, notably all of the
      ## attribute mappings have a default value that this config overrides, you can read more about these default values
      ## at https://www.authelia.com/reference/guides/ldap/#defaults
      implementation: 'lldap'

      ## The address for the ldap server. Format: <scheme>://<address>[:<port>].
      ## Scheme can be ldap or ldaps in the format (port optional).
      address: 'ldap://iam-ldap.default:3890'

      ## Connection Timeout.
      timeout: '5 seconds'

      ## Use StartTLS with the LDAP connection.
      start_tls: false

      ## The base dn for every LDAP query.
      base_dn: 'DC=acitrus,DC=cn'

      ## An additional dn to define the scope to all users.
      additional_users_dn: 'OU=people'

      ## The users filter used in search queries to find the user profile based on input filled in login form.
      ## Various placeholders are available in the user filter:
      ## - {input} is a placeholder replaced by what the user inputs in the login form.
      ## - {username_attribute} is a mandatory placeholder replaced by what is configured in `username_attribute`.
      ## - {mail_attribute} is a placeholder replaced by what is configured in `mail_attribute`.
      ## - DON'T USE - {0} is an alias for {input} supported for backward compatibility but it will be deprecated in later
      ##   versions, so please don't use it.
      ##
      ## Recommended settings are as follows:
      ## - Microsoft Active Directory: (&({username_attribute}={input})(objectCategory=person)(objectClass=user))
      ## - OpenLDAP:
      ##   - (&({username_attribute}={input})(objectClass=person))
      ##   - (&({username_attribute}={input})(objectClass=inetOrgPerson))
      ##
      ## To allow sign in both with username and email, one can use a filter like
      ## (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
      users_filter: '(&({username_attribute}={input})(objectClass=person))'

      ## An additional dn to define the scope of groups.
      additional_groups_dn: 'OU=groups'

      ## The groups filter used in search queries to find the groups of the user.
      ## - {input} is a placeholder replaced by what the user inputs in the login form.
      ## - {username} is a placeholder replace by the username stored in LDAP (based on `username_attribute`).
      ## - {dn} is a matcher replaced by the user distinguished name, aka, user DN.
      ## - {username_attribute} is a placeholder replaced by what is configured in `username_attribute`.
      ## - {mail_attribute} is a placeholder replaced by what is configured in `mail_attribute`.
      ## - DON'T USE - {0} is an alias for {input} supported for backward compatibility but it will be deprecated in later
      ##   versions, so please don't use it.
      ## - DON'T USE - {1} is an alias for {username} supported for backward compatibility but it will be deprecated in
      ##   later version, so please don't use it.
      ##
      ## If your groups use the `groupOfUniqueNames` structure use this instead:
      ##    (&(uniquemember={dn})(objectclass=groupOfUniqueNames))
      groups_filter: '(member={dn})'

      ## The username of the admin user.
      user: 'uid=reader,ou=people,dc=acitrus,dc=cn'

      password:
        ## Disables this secret and leaves configuring it entirely up to you.
        disabled: false

        ## The secret name. The ~ name is special as it is the secret we generate either automatically or via the
        ## secret_value option below.
        secret_name: ~

        ## The value of a generated secret when using the ~ secret_name.
        value: 'qQKMdVrLmbuYXu1eGxTC'

        ## The path to the secret. If it has a '/' prefix it's assumed to be an absolute path within the pod. Otherwise
        ## it uses the format '{mountPath}/{secret_name}/{path}' where '{mountPath}' refers to the 'secret.mountPath'
        ## value, '{secret_name}' is the secret_name above, and '{path}' is this value.
        path: 'authentication.ldap.password.txt'

      attributes:
        distinguished_name: 'distinguishedName'
        username: 'uid'
        mail: 'mail'
        member_of: 'memberOf'
        group_name: 'cn'

  session:
    redis:
      enabled: true
      enabledSecret: true
      host: 'redis-master.default'
      port: 6379

    encryption_key:
      ## The value of a generated secret when using the ~ secret_name.
      value: 'X6awd^.ZGwcfEacfcGy!HQ!)H043T2CbqG3kVH]C!#.0%>F8bM>Z@rGQg,tce2rKp~j-5knK=)F~}t4H+zZqQ?x}Qnn!aMan^q6>'

    cookies:
      - domain: 'acitrus.cn'
        subdomain: 'auth'
        authelia_url: 'https://auth.acitrus.cn'
        name: 'authelia_session'
        # same_site: 'lax'
        # inactivity: '5m'
        # expiration: '1h'
        # remember_me: '1d'

  storage:
    encryption_key:
      value: 'J~d_+Pyxy!e4e:Q-)W8pe0D8.@^*qD2^sh1ZczE>N-wns7WP-]tWk27P.RmLNwjtPLW2y9,KDv3Ump50PGsdsW>~Qwq=Y5Fa)ru*'

  notifier:
    filesystem:
      enabled: true
      filename: '/config/notification.txt'

  access_control:
    secret:
      enabled: true

    # It must be either 'bypass', 'one_factor', 'two_factor' or 'deny'.
    rules:
      # kafka ui
      - domain: 'kafka.acitrus.cn'
        policy: 'bypass'
        methods:
          - 'GET'

      - domain: 'kafka.acitrus.cn'
        policy: 'one_factor'
        subject:
          - 'group:public_readonly'
          - 'group:public_read_write'

      # nacos
      - domain: 'nacos.acitrus.cn'
        policy: 'bypass'
        methods:
          - 'GET'
      - domain: 'nacos.acitrus.cn'
        subject:
          - 'group:public_read_write'
        policy: 'one_factor'
      # home
      - domain: 'home.acitrus.cn'
        subject:
          - 'group:public_readonly'
        policy: 'one_factor'
        methods:
          - 'GET'
      - domain: 'home.acitrus.cn'
        subject:
          - 'group:public_read_write'
        policy: 'one_factor'

  identity_providers:
    oidc:
      ## Enables this in the config map. Currently in beta stage.
      ## See https://www.authelia.com/r/openid-connect/
      enabled: true

      # https://www.authelia.com/configuration/identity-providers/openid-connect/provider/#authorization_policies
      authorization_policies: { }

      clients:
        - client_id: '58XXRbiqcdfaeq8DaPP91zYVTw2of4LqVrKdzirQiJDKoANfZDFgtduTYWbtqxE2'
          client_name: 'KAFKA UI'
          # https://www.authelia.com/integration/openid-connect/frequently-asked-questions/#client-secret
          # T1Q1DYTK40unEDECju5Tir.UBOx4o0awLoBa8SZhpBudos.yZ.IHNNs3pP-6Hb05
          # $pbkdf2-sha512$310000$Tf2HocbXV4zIcqTb0SKsmg$0N7GXKDMWYq2Rd4ns3GPAlEk2jrd532GzjNy0gzM9NHBUG43WVEhz.FseMjwZdodqco93hYYWIxkQA4KxasSCA
          client_secret: '$pbkdf2-sha512$310000$Tf2HocbXV4zIcqTb0SKsmg$0N7GXKDMWYq2Rd4ns3GPAlEk2jrd532GzjNy0gzM9NHBUG43WVEhz.FseMjwZdodqco93hYYWIxkQA4KxasSCA'  # The digest of 'insecure_secret'.
          redirect_uris:
            - 'https://kafka.acitrus.cn/oauth/callback/auth.acitrus.cn'
          authorization_policy: 'one_factor'