authelia:
  pod:
    kind: Deployment
    replicas: 1

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false

  configMap:
    totp:
      disable: true

    webauthn:
      disable: true

    server:
      endpoints:
        automatic_authz_implementations:
          - ForwardAuth

    access_control:
      default_policy: one_factor

    authentication_backend:
      password_reset:
        disable: true
      password_change:
        disable: true

    storage:
      local:
        enabled: false

    notifier:
      filesystem:
        enabled: true
        filename: /config/notification.txt

  persistence:
    enabled: false

autheliaSecrets:
  enabled: false
  ldapPassword: ""
  sessionEncryptionKey: ""
  storageEncryptionKey: ""
  resetPasswordJwtSecret: ""
  redisPassword: ""
  postgresPassword: ""

autheliaIngress:
  enabled: false
  name: authelia
  host: ""
  entryPoints: []
  service:
    name: authelia
    port: 80
  tls: {}

autheliaForwardAuth:
  enabled: false
  name: authelia-forwardauth
  address: ""
  trustForwardHeader: true
  authResponseHeaders:
    - Remote-User
    - Remote-Name
    - Remote-Email
    - Remote-Groups
