repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: traefik
    url: https://traefik.github.io/charts
  - name: authelia
    url: https://charts.authelia.com

helmDefaults:
  atomic: true
  wait: true
  waitForJobs: true
  timeout: 600

---

environments:
  dev:
    values:
      - environments/dev/values.yaml

---

releases:
  - name: test-charts
    namespace: app
    createNamespace: true
    chart: ./charts/test-charts
    values:
      - ./environments/{{ .Environment.Name }}/test-charts/values.yaml

  - name: redis
    namespace: infra
    createNamespace: true
    chart: ./charts/redis
    values:
      - ./environments/{{ .Environment.Name }}/redis/values.yaml

  - name: postgresql
    namespace: infra
    createNamespace: true
    chart: ./charts/postgresql
    values:
      - ./environments/{{ .Environment.Name }}/postgresql/values.yaml

  - name: lldap
    namespace: infra
    createNamespace: true
    chart: ./charts/lldap
    needs:
      - infra/postgresql
    values:
      - ./environments/{{ .Environment.Name }}/lldap/values.yaml

  - name: rabbitmq
    namespace: infra
    createNamespace: true
    chart: ./charts/rabbitmq
    values:
      - ./environments/{{ .Environment.Name }}/rabbitmq/values.yaml

  - name: authelia
    namespace: infra
    createNamespace: true
    chart: ./charts/authelia
    needs:
      - infra/lldap
    values:
      - ./environments/{{ .Environment.Name }}/authelia/values.yaml

  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: ./charts/traefik
    values:
      - ./environments/{{ .Environment.Name }}/traefik/values.yaml
