apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "developer" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: gateway-clusterrolebinding
  namespace: gateway
subjects:
  - kind: ServiceAccount
    name: gateway-serviceaccount # Name is case sensitive
    # apiGroup: rbac.authorization.k8s.io
    namespace: gateway
roleRef:
  kind: ClusterRole
  name: gateway-clusterrole
  apiGroup: rbac.authorization.k8s.io
