traefik:
  image:
    registry: registry.cn-shenzhen.aliyuncs.com
    repository: gravitation/traefik
    tag: v3.7.12

  deployment:
    kind: DaemonSet

  service:
    spec:
      type: LoadBalancer
      externalTrafficPolicy: Local

  tolerations:
    - key: node.kubernetes.io/unschedulable
      operator: Exists
      effect: NoSchedule

  ports:
    gravitation:
      port: 1024
      expose:
        default: true
      exposedPort: 1024
      protocol: TCP

    websecure:
      http3:
        enabled: true
        advertisedPort: 443
      http:
        tls:
          enabled: true
          options: ""

  tlsStore:
    default:
      defaultCertificate:
        secretName: acitrus-tls

  ingressRoute:
    dashboard:
      enabled: true
      matchRule: Host(`traefik.acitrus.cn`)
      entryPoints:
        - websecure
        - web
      middlewares:
        - name: authelia-forwardauth
          namespace: infra

  providers:
    kubernetesCRD:
      allowCrossNamespace: true
      enabled: true
