apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: casdoor-route
  namespace: casdoor
spec:
  http:
    - name: casdoor-route
      match:
        hosts:
          - auth.acitrus.cn
        paths:
          - /*
      backends:
        - serviceName: casdoor
          servicePort: 8000
      websocket: true
      plugins:
        - name: redirect
          enable: false
          config:
            http_to_https: true
#        - name: real-ip
#          enable: true
#          config:
#            source: "http_x_forwarded_for"