apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nacos.acitrus.cn
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    gethomepage.dev/href: "https://nacos.acitrus.cn"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "r-nacos是一个用rust实现的nacos服务"
    gethomepage.dev/group: Public
    gethomepage.dev/name: nacos
    gethomepage.dev/ping: "nacos.acitrus.cn"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=rnacos"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # https://doc.traefik.io/traefik/middlewares/overview/
    - kind: Rule
      match: Host(`nacos.acitrus.cn`)
      services:
        - kind: Service
          name: rnacos
          port: 8848
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
      middlewares:
        - name: http-to-https
        - name: 'forwardauth-authelia' # name of your middleware, as defined in your middleware.yml
          namespace: 'default'