# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r27
    - name: zookeeper
      image: docker.io/bitnami/zookeeper:3.9.2-debian-12-r11
apiVersion: v2
appVersion: 3.9.2
dependencies:
  - name: common
    repository: https://charts.acitrus.cn
    tags:
      - common
    version: 1.x.x
description: Apache ZooKeeper provides a reliable, centralized register of configuration data and services for distributed applications.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/zookeeper/img/zookeeper-stack-220x234.png
keywords:
  - zookeeper
maintainers:
  - name: Broadcom, Inc. All Rights Reserved.
    url: https://github.com/bitnami/charts
name: zookeeper
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/zookeeper
version: 1.0.0
