version: "3.9"
services:
  zookeeper:
    #    build:
    #      dockerfile: ./DockerFile
    image: local:dev
    configs:
      - source: test_dir
        target: /opt/test
        mode: 0440
      - source: zoo_cfg
        target: /conf/zoo.cfg

    env_file:
      - .env
    environment:
      - sys_t1=${ZOOKEEPER_REPLICAS:-1}
      - COMPOSE_SERVICE_NAME=zookeeper

    networks:
      - component-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 70M
        reservations:
          cpus: "0.1"
          memory: 50M
      #      mode: replicated
      replicas: 4
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5



networks:
  component-network:
    external: false
    name: component-network
    labels:
      - "key=value"

configs:
  test_dir:
    name: "test"
    file: ./

  zoo_cfg:
    name: "zoo.cfg"
    file: ./config/zoo.cfg
