apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lldap.fullname" . }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lldap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lldap.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: lldap
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LLDAP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ required "secret.existingSecret is required" .Values.secret.existingSecret | quote }}
                  key: {{ required "secret.keys.jwtSecret is required" .Values.secret.keys.jwtSecret | quote }}
            - name: LLDAP_KEY_SEED
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.existingSecret | quote }}
                  key: {{ required "secret.keys.keySeed is required" .Values.secret.keys.keySeed | quote }}
            - name: LLDAP_LDAP_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.existingSecret | quote }}
                  key: {{ required "secret.keys.adminPassword is required" .Values.secret.keys.adminPassword | quote }}
            - name: LLDAP_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.existingSecret | quote }}
                  key: {{ required "secret.keys.databaseUrl is required" .Values.secret.keys.databaseUrl | quote }}
            - name: LLDAP_LDAP_BASE_DN
              value: {{ required "config.baseDn is required" .Values.config.baseDn | quote }}
            - name: LLDAP_HTTP_URL
              value: {{ required "config.httpUrl is required" .Values.config.httpUrl | quote }}
            - name: TZ
              value: {{ .Values.config.timezone | quote }}
          ports:
            - name: ldap
              containerPort: {{ .Values.service.ldapPort }}
              protocol: TCP
            - name: web
              containerPort: {{ .Values.service.webPort }}
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: web
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
          readinessProbe:
            tcpSocket:
              port: ldap
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            tcpSocket:
              port: web
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
