{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingress.name | quote }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entryPoints | nindent 4 }}
  routes:
    - kind: Rule
      match: 'Host(`{{ required "ingress.host is required when ingress.enabled=true" .Values.ingress.host }}`)'
      services:
        - name: {{ include "lldap.fullname" . | quote }}
          port: {{ .Values.service.webPort }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
