apiVersion: v1
kind: Service
metadata:
  name: {{ include "lldap.fullname" . }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ldap
      port: {{ .Values.service.ldapPort }}
      targetPort: ldap
      protocol: TCP
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
      protocol: TCP
  selector:
    {{- include "lldap.selectorLabels" . | nindent 4 }}
