apiVersion: v1
kind: Service
metadata:
  name: console-service
  namespace: conduktor

spec:
  selector:
    app: console
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
#  clusterIP: None