fullnameOverride: "rnacos"
replicaCount: 1

image:
  repository: qingpan/rnacos
  pullPolicy: IfNotPresent

persistence:
  size: 2Gi

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

extraEnvVars:
  - name: RNACOS_CONSOLE_ENABLE_CAPTCHA
    value: "false"
  - name: RNACOS_ENABLE_NO_AUTH_CONSOLE
    value: "true"