apiVersion: v1
kind: Service
metadata:
  name: hive-server-service
  labels:
    app: hive-server-service
spec:
  #  ports:
  #    - port: 2181
  #      name: client
  #      targetPort: 2181
  #      protocol: TCP

  clusterIP: None
  selector:
    app: hive-server