apiVersion: v1
kind: Service
metadata:
  name: tez-service
  labels:
    app: tez-server
spec:
    ports:
      - port: 80
        name: web
        targetPort: 80
        protocol: TCP
    type: ClusterIP
    selector:
      app: tez-server