apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: teamcity
spec:
  selector:
    app: agent
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

  clusterIP: None
  