apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: teamcity
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8111
      targetPort: 8111
#  type: LoadBalancer
  clusterIP: None
  