apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rabbitmq.acitrus.cn
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    gethomepage.dev/href: "https://rabbitmq.acitrus.cn"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: rabbitmq
    gethomepage.dev/group: Storage
    gethomepage.dev/name: rabbitmq
    gethomepage.dev/ping: "https://rabbitmq.acitrus.cn"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=rabbitmq"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # https://doc.traefik.io/traefik/middlewares/overview/
    - kind: Rule
      match: Host(`rabbitmq.acitrus.cn`)
      services:
        - kind: Service
          name: rabbitmq
          port: 15672
      middlewares:
        - name: http-to-https
          namespace: 'default'
        - name: 'forwardauth-authelia' # name of your middleware, as defined in your middleware.yml
          namespace: 'default'