apiVersion: traefik.io/v1alpha1
# https://doc.traefik.io/traefik/middlewares/http/redirectscheme/
kind: Middleware
metadata:
  name: public-cors
  namespace: default
spec:
  headers:
    #    customResponseHeaders:
    #      Access-Control-Allow-Origin: "http://soulchild.cn:8080"
    #      Access-Control-Allow-Methods: "*"
    #      Access-Control-Allow-Headers: "*"
    # 另一种写法
    accessControlAllowMethods:
      - "*"
    accessControlAllowOriginList:
      - "https://rabbitmq.acitrus.cn"
    accessControlAllowHeaders:
      - "*"
    #accessControlMaxAge: 100
    #addVaryHeader: true