# 版本信息
apiVersion: apps/v1

# 类型
kind: StatefulSet

# 元数据
metadata:
  name: namenode
  labels:
    app: namenode

spec:


  # ----------------- 1.多副本策略 -----------------
  replicas: 1
  # 滚动更新
  updateStrategy:
    type: RollingUpdate
  # 最短就绪时间
  minReadySeconds: 10
  # ----------------- 1.多副本策略 -----------------

  serviceName: ss

  # 选择器
  selector:
    matchLabels:
      # 必须匹配 .spec.template.metadata.labels
      app: namenode




  # 模版信息
  template:
    metadata:
      name: namenode
      # 必须匹配 .spec.selector.matchLabels
      labels:
        app: namenode
    spec:
      containers:
        - name: Title
          image: Image
          imagePullPolicy: IfNotPresent

          # 资源限制
          resources:
            limits:
              memory: 500MI
            requests:
              memory: 10Mi

          ports:
            - containerPort: 9870
              protocol: TCP

          # 存活监测
          #          livenessProbe:
          #            tcpSocket:
          #              port: 2180
          #            initialDelaySeconds: 30
          #            periodSeconds: 10

          volumeMounts:
            - mountPath: /opt/data/
              name: testDir
      restartPolicy: Always


  # 持久卷
  volumeClaimTemplates:
    - metadata:
        name: testDir
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
          limits:
            storage: 1Gi


---
apiVersion: v1
kind: Service
metadata:
  name: namenode
  labels:
    app: namenode
    service: namenode
spec:

  ports:
    - port: 9870
      name: http
      targetPort: 9870
      protocol: TCP

  clusterIP: None
  selector:
    app: namenode
    service: namenode

