resources:
  - Storage/Namespace/homepage.yaml
  - AccessControl/ClusterRole/homepage.yaml
  - AccessControl/ClusterRoleBinding/homepage.yaml
  - AccessControl/ServiceAccount/homepage.yaml
  - Config/ConfigMap/homepage.yaml
  - Config/Secret/homepage.yaml
  - Network/Middleware/http-to-https.yaml
  - Network/IngressRoute/homepage.yaml
  - Network/Service/homepage.yaml
  - Workload/Deployment/homepage.yaml