{{- if .Values.autheliaForwardAuth.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.autheliaForwardAuth.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  forwardAuth:
    address: {{ required "autheliaForwardAuth.address is required" .Values.autheliaForwardAuth.address | quote }}
    trustForwardHeader: {{ .Values.autheliaForwardAuth.trustForwardHeader }}
    authResponseHeaders:
      {{- toYaml .Values.autheliaForwardAuth.authResponseHeaders | nindent 6 }}
{{- end }}
