{{- if .Values.autheliaSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.autheliaSecrets.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  authentication.ldap.password.txt: {{ required "autheliaSecrets.ldapPassword is required when autheliaSecrets.enabled=true" .Values.autheliaSecrets.ldapPassword | quote }}
  session.encryption.key: {{ required "autheliaSecrets.sessionEncryptionKey is required when autheliaSecrets.enabled=true" .Values.autheliaSecrets.sessionEncryptionKey | quote }}
  storage.encryption.key: {{ required "autheliaSecrets.storageEncryptionKey is required when autheliaSecrets.enabled=true" .Values.autheliaSecrets.storageEncryptionKey | quote }}
  identity_validation.reset_password.jwt.hmac.key: {{ required "autheliaSecrets.resetPasswordJwtSecret is required when autheliaSecrets.enabled=true" .Values.autheliaSecrets.resetPasswordJwtSecret | quote }}
{{- end }}
