{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "service-atlas.fullname" . }}
  labels:
    {{- include "service-atlas.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingressRoute.entryPoints | nindent 4 }}
  routes:
    - kind: Rule
      match: 'Host(`{{ required "ingressRoute.host is required when ingressRoute is enabled" .Values.ingressRoute.host }}`)'
      {{- with .Values.ingressRoute.middlewares }}
      middlewares:
        {{- range . }}
        - name: {{ .name | quote }}
          {{- with .namespace }}
          namespace: {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      services:
        - name: {{ include "service-atlas.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    {{- toYaml .Values.ingressRoute.tls | nindent 4 }}
{{- end }}
