# https://blog.csdn.net/sinat_32188225/article/details/124117638
envFrom:
  - secretRef:
      name: alidns

ports:
  websecure:
    http3:
      ## -- Enable HTTP/3 on the entrypoint
      ## Enabling it will also enable http3 experimental feature
      ## https://doc.traefik.io/traefik/routing/entrypoints/#http3
      ## There are known limitations when trying to listen on same ports for
      ## TCP & UDP (Http3). There is a workaround in this chart using dual Service.
      ## https://github.com/kubernetes/kubernetes/issues/47249#issuecomment-587960741
      enabled: true
      advertisedPort: 443  # @schema type:[integer, null]; minimum:0
    tls:
      enabled: true
      options: ""
      certResolver: "leresolver"
      domains:
        - main: "acitrus.cn"
          sans:
            - "*.acitrus.cn"


# -- Certificates resolvers configuration.
# Ref: https://doc.traefik.io/traefik/https/acme/#certificate-resolvers
# See EXAMPLES.md for more details.
certificatesResolvers:
  leresolver:
    acme:
      storage: /data/acme.json
      email: "mail@acitrus.cn"
      dnsChallenge:
        provider: alidns
        delayBeforeCheck: 0

persistence:
  # -- Enable persistence using Persistent Volume Claims
  # ref: http://kubernetes.io/docs/user-guide/persistent-volumes/.
  # It can be used to store TLS certificates along with `certificatesResolvers.<name>.acme.storage`  option
  enabled: true

deployment:
  initContainers:
    # The "volume-permissions" init container is required if you run into permission issues.
    # Related issue: https://github.com/traefik/traefik-helm-chart/issues/396
    - name: volume-permissions
      image: busybox:latest
      command: [ "sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json" ]
      volumeMounts:
        - name: data
          mountPath: /data

ingressRoute:
  dashboard:
    # -- Create an IngressRoute for the dashboard
    enabled: true