aliyunSecret:
  enabled: false
  name: alidns
  accessKey: ""
  secretKey: ""

traefik:
  env:
    - name: CASDOOR_ENFORCER_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: casdoor-traefik-auth
          key: client-secret
          optional: true

  experimental:
    plugins:
      traefikoidc:
        moduleName: github.com/lukaszraczylo/traefikoidc
        version: v1.0.29
    localPlugins:
      casdoorEnforcer:
        type: localPath
        moduleName: github.com/because-of-you/casdoor-enforcer
        volumeName: casdoor-enforcer-plugin
        mountPath: /plugins-local/src/github.com/because-of-you/casdoor-enforcer

  deployment:
    additionalVolumes:
      - name: casdoor-enforcer-plugin
        configMap:
          name: casdoor-enforcer-plugin

casdoorAuthorization:
  enabled: false
  providerURL: ""
  enforceEndpoint: ""
  clientID: ""
  permissionID: ""
  oidc:
    callbackURL: /oauth2/callback
    logoutURL: /oauth2/logout
    postLogoutRedirectURI: /
    cookieDomain: ""
    forceHTTPS: true
    strictAudienceValidation: true
  enforcer:
    subjectHeader: X-Casdoor-Subject
    timeout: 2s
  middlewares:
    oidcName: casdoor-oidc
    enforcerName: casdoor-enforcer
    chainName: casdoor-protected
