apiVersion: v2
name: casdoor
description: Wrapper chart for Casdoor with local values
type: application
version: 0.1.0
appVersion: "3.125.0"
dependencies:
  - name: casdoor-helm-charts
    version: 3.125.0
    repository: oci://registry-1.docker.io/casbin
