apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: kubesphere-route
  namespace: kubesphere-system
spec:
  http:
    - name: kubesphere-route-ui
      match:
        hosts:
          - dev.acitrus.cn
        paths:
          - /*
      backends:
        - serviceName: ks-console
          servicePort: 80
      websocket: true
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true