apiVersion: v1
kind: Service
metadata:
  name: datanode-service
  labels:
    app: datanode
spec:
  ports:
    - port: 9870
      name: datanode-web
      targetPort: 9870
      protocol: TCP

  clusterIP: None
  selector:
    app: datanode