apiVersion: v1
kind: Service
metadata:
  name: namenode-service
  labels:
    app: namenode
spec:
  ports:
    - port: 9870
      name: namenode-web
      targetPort: 9870
      protocol: TCP

  clusterIP: None
  selector:
    app: namenode