apiVersion: v1
kind: Service
metadata:
  name: resourcemanager-service
  labels:
    app: resourcemanager
spec:
  ports:
    - port: 8088
      name: resourcemanager-web
      targetPort: 8088
      protocol: TCP

    - port: 19888
      name: resourcemanager-history-web
      targetPort: 19888
      protocol: TCP

  clusterIP: None
  selector:
    app: resourcemanager