apiVersion: v1
kind: Service
metadata:
  name: timelineserver-service
  labels:
    app: timelineserver
spec:
  ports:
    - port: 8188
      name: timelineserver-web
      targetPort: 8188
      protocol: TCP

  clusterIP: None
  selector:
    app: timelineserver