apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: namenode
  labels:
    app: namenode

spec:
  replicas: 1

  updateStrategy:
    type: RollingUpdate

  minReadySeconds: 10
  serviceName: namenode-service

  selector:
    matchLabels:
      app: namenode

  template:
    metadata:
      name: namenode
      labels:
        app: namenode

    spec:
      # nodeName: local-1-6c-32g-10m
#      nodeSelector:
#        storage: "true"

      initContainers:
        - name: hadoop-resource-init
          image: wfybelief/hadoop:3.3.6
          imagePullPolicy: IfNotPresent
          command:
            - busybox
            - sh
            - -c
          args:
            - |
              tar -zxvf /opt/component/storage/hadoop/hadoop-*.tar.gz -C /opt/component/hadoop --strip-components 1
          volumeMounts:
            - mountPath: /opt/component/hadoop
              name: hadoop-resource-volume

      containers:
        - name: namenode
          image: wfybelief/jdk-8:0.0.4
          imagePullPolicy: IfNotPresent

          command:
            - busybox
            - sh
            - entrypoint.sh
          args:
            - hdfs
            - namenode
          env:
            - name: HDFS_NAMENODE_OPTS
              value: -XX:+UseContainerSupport
                -XX:InitialRAMPercentage=60.0
                -XX:MaxRAMPercentage=60.0 
                -Xshareclasses 
                -Xtune:virtualized 
                -Xquickstart 

          resources:
            limits:
              cpu: 2000m  # 2048 / 1
              memory: 2048Mi
            requests:
              memory: 10Mi
              cpu: 1m

          ports:
            - containerPort: 9870
              protocol: TCP

          volumeMounts:
            - mountPath: /opt/component/storage/
              name: component-storage
              readOnly: false

            - mountPath: /opt/component/hadoop
              name: hadoop-resource-volume
              readOnly: false

            - mountPath: /entrypoint.sh
              subPath: entrypoint.sh
              name: namenode-config-volume
              readOnly: true

            - mountPath: /opt/component/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
              name: namenode-config-volume
              readOnly: true

            - mountPath: /opt/component/hadoop/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
              name: namenode-config-volume
              readOnly: true

            - mountPath: /opt/component/hadoop/etc/hadoop/mapred-site.xml
              subPath: mapred-site.xml
              name: namenode-config-volume
              readOnly: true

            - mountPath: /opt/component/hadoop/etc/hadoop/yarn-site.xml
              subPath: yarn-site.xml
              name: namenode-config-volume
              readOnly: true

      volumes:
        - name: namenode-config-volume

          configMap:
            name: hadoop-configmap

            items:
              - key: core-site.xml
                path: core-site.xml

              - key: hdfs-site.xml
                path: hdfs-site.xml

              - key: mapred-site.xml
                path: mapred-site.xml

              - key: yarn-site.xml
                path: yarn-site.xml

              - key: entrypoint.sh
                path: entrypoint.sh

        - name: hadoop-resource-volume
          emptyDir:
            { }

      restartPolicy: Always


  # 持久卷
  volumeClaimTemplates:
    - metadata:
        name: component-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path # csi-disk-ssd | hostpath
        resources:
          requests:
            storage: 1Gi
          limits:
            storage: 10Gi