apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nodemanager
  labels:
    app: nodemanager

spec:
  replicas: 3

  updateStrategy:
    type: RollingUpdate

  minReadySeconds: 10
  serviceName: nodemanager-service

  selector:
    matchLabels:
      app: nodemanager

  template:
    metadata:
      name: nodemanager
      labels:
        app: nodemanager

    spec:
      initContainers:
        - name: hadoop-resource-init
          image: wfybelief/hadoop:3.3.6
          imagePullPolicy: IfNotPresent
          command:
            - busybox
            - sh
            - -c
          args:
            - |
              tar -zxvf /opt/component/storage/hadoop/hadoop-*.tar.gz -C /opt/component/hadoop --strip-components 1
          volumeMounts:
            - mountPath: /opt/component/hadoop
              name: hadoop-resource-volume


      containers:
        - name: nodemanager
          image: wfybelief/jdk-8:0.0.4
          imagePullPolicy: IfNotPresent

          command:
            - busybox
            - sh
            - entrypoint.sh
          args:
            - yarn
            - nodemanager
          env:
            - name: YARN_NODEMANAGER_OPTS
              value: -XX:+UseContainerSupport
                -XX:InitialRAMPercentage=20.0
                -XX:MaxRAMPercentage=20.0
                -Xshareclasses
                -Xtune:virtualized
                -Xquickstart

          resources:
            limits:
              cpu: 2000m
              # 2048 / 1
              memory: 4096Mi
            requests:
              cpu: 1m
              memory: 10Mi

          ports:
            - containerPort: 9870
              protocol: TCP

          volumeMounts:

            - mountPath: /opt/component/hadoop
              name: hadoop-resource-volume
              readOnly: false

            - mountPath: /entrypoint.sh
              subPath: entrypoint.sh
              name: nodemanager-config-volume
              readOnly: true

            - mountPath: /opt/component/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
              name: nodemanager-config-volume
              readOnly: true

            - mountPath: /opt/component/hadoop/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
              name: nodemanager-config-volume
              readOnly: true

            - mountPath: /opt/component/hadoop/etc/hadoop/mapred-site.xml
              subPath: mapred-site.xml
              name: nodemanager-config-volume
              readOnly: true

            - mountPath: /opt/component/hadoop/etc/hadoop/yarn-site.xml
              subPath: yarn-site.xml
              name: nodemanager-config-volume
              readOnly: true

      volumes:
        - name: nodemanager-config-volume

          configMap:
            name: hadoop-configmap

            items:
              - key: core-site.xml
                path: core-site.xml

              - key: hdfs-site.xml
                path: hdfs-site.xml

              - key: mapred-site.xml
                path: mapred-site.xml

              - key: yarn-site.xml
                path: yarn-site.xml

              - key: entrypoint.sh
                path: entrypoint.sh

        - name: hadoop-resource-volume
          emptyDir:
            { }

      restartPolicy: Always