# Redirect to https
apiVersion: traefik.io/v1alpha1
# https://doc.traefik.io/traefik/middlewares/http/redirectscheme/
kind: Middleware
metadata:
  name: http-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true