# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: jmx-exporter
      image: registry.cn-shenzhen.aliyuncs.com/gravitation/jmx-exporter:1.0.1-debian-12-r5
    - name: kafka
      image: registry.cn-shenzhen.aliyuncs.com/gravitation/kafka:3.8.0-debian-12-r2
    - name: kubectl
      image: registry.cn-shenzhen.aliyuncs.com/gravitation/kubectl:1.30.3-debian-12-r5
    - name: os-shell
      image: registry.cn-shenzhen.aliyuncs.com/gravitation/os-shell:12
apiVersion: v2
appVersion: 3.8.0
dependencies:
  - condition: zookeeper.enabled
    name: zookeeper
    repository: https://charts.acitrus.cn
    version: 1.x.x
  - name: common
    repository: https://charts.acitrus.cn
    tags:
      - bitnami-common
    version: 1.x.x
description: Apache Kafka is a distributed streaming platform designed to build real-time pipelines and can be used as a message broker or as a replacement for a log aggregation solution for big data applications.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-220x234.png
keywords:
  - kafka
  - zookeeper
  - streaming
  - producer
  - consumer
maintainers:
  - name: Broadcom, Inc. All Rights Reserved.
    url: https://github.com/bitnami/charts
name: kafka
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/kafka
version: 1.0.0
