extraEnvVars:
  - name: MINIO_IDENTITY_OPENID_CONFIG_URL
    value: https://auth.acitrus.cn/.well-known/openid-configuration
  - name: MINIO_IDENTITY_OPENID_CLIENT_ID
    value: minio
  - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
    value: IeuNPrAVzd1hPRv.ZzCgSHAsqltWSXVov4Z.jM0qGYQX4M~zpPZ.YWYlAswAQB.S
  - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
    value: https://minio.acitrus.cn/oauth_callback
  #  - name: MINIO_IDENTITY_OPENID_ROLE_POLICY
  #    value: '{"groups":{"lldap_admin":"consoleAdmin","public_read_write":"readwrite","public_readonly":"readonly"}}'
  - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
    value: groups
  - name: MINIO_IDENTITY_OPENID_DISPLAY_NAME
    value: "auth.acitrus.cn"
provisioning:
  enabled: true
  policies:
    # https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html#id3
    - name: public_read_write
      statements:
        - resources:
            - "arn:aws:s3:::my-bucket/${jwt:preferred_username}/*"
          actions:
            - "s3:*"
          effect: "Allow"