FROM ubuntu:latest
LABEL authors="wangfeiyu"

ENTRYPOINT ["top", "-b"]

# openj9

# myid

# server.1

#0
#1
#2
#
#0-n
#
#statefuleset
#zookeeper-0 -> 0 0          standalone off
#zookeeper-1 -> 1 0,1
#zookeeper-2 -> 2 0,1,2
#
#kafka <- zookeeper
#
#kafka <- | service network zookeeper-headless-network | {zk0,zk1,zk2}
#
#0 -> final var ｜ share 内存  scc shared classes cache
#1 ->
