apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kafka.acitrus.cn
  namespace: conduktor
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    gethomepage.dev/href: "https://kafka.acitrus.cn"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: 一款现代化的 kafka ui | auth单点登录
    gethomepage.dev/group: Public
    # gethomepage.dev/icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/homepage.png
    gethomepage.dev/name: Kafka UI
    gethomepage.dev/ping: kafka.acitrus.cn
    gethomepage.dev/namespace: conduktor
    gethomepage.dev/pod-selector: >-
      app.kubernetes.io/instance in (
          gateway,
          console
      )
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # https://doc.traefik.io/traefik/middlewares/overview/
    - kind: Rule
      match: Host(`kafka.acitrus.cn`)
      services:
        - kind: Service
          name: console
          port: 80
      middlewares:
        - name: http-to-https
          namespace: 'default'
        - name: 'forwardauth-authelia' # name of your middleware, as defined in your middleware.yml
          namespace: 'default'