apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: conduktor-route
  namespace: conduktor
spec:
  http:
    - name: kafka-route-console
      match:
        hosts:
          - kafka.acitrus.cn
        #          - kafka3.acitrus.cn
        paths:
          - /*
      backends:
        - serviceName: console
          servicePort: 80
      websocket: true
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
        - name: kafka-logger
          enable: true
          config:
            kafka_topic: apisix_conduktor_log
            batch_max_size: 1
            name: "kafka logger"
            brokers:
              - host: "kafka.default"
                port: 9092

        - name: real-ip
          enable: true
          config:
            source: "http_x_forwarded_for"

        - name: request-id
          enable: true
