nameOverride: "iam"
fullnameOverride: ""

lldap:
  # -- Base DN for LDAP.
  # This is usually your domain name, and is used as a namespace for your users. The choice is
  # arbitrary, but will be needed to configure the LDAP integration with other services. The sample
  # value is for "acitrus.cn", but you can extend it with as many "dc" as you want, and you don't
  # actually need to own the domain name.
  baseDN: "dc=acitrus,dc=cn"

  # -- Random secret for JWT signature.
  # This secret should be random, and should be shared with application servers that need to
  # consume the JWTs. Changing this secret will invalidate all user sessions and require them
  # to re-login. You can generate it with (on linux):
  # LC_ALL=C tr -dc 'A-Za-z0-9!#%&'\''()*+,-./:;<=>?@[\]^_{|}~' </dev/urandom | head -c 32; echo ''
  jwtSecret: "9EB.W43B2TGHL*8=RA-?C,BuU.LF4Ai95_UBv_i0Q9nG48?1cMJ>YAxTGCK2F0sHxQUKDPy8Q)U@m!w5+xeo%p5d0re}.iX)gZDV"

  # -- Admin username.
  # For the LDAP interface, a value of "admin" here will create the LDAP user
  # "cn=admin,ou=people,dc=acitrus,dc=cn" (with the base DN above). For the administration
  # interface, this is the username.
  ldapUserDN: "admin"

  # -- Admin password.
  # Password for the admin account, both for the LDAP bind and for the administration interface.
  # It is only used when initially creating the admin user. It should be minimum 8 characters long.
  # Note: you can create another admin user for user administration, this is just the default one.
  ldapUserPass: "f7ED@vN0yj0CxHx18vjp"

  # -- Seed to generate the server private key. This can be any random string, the recnmendation
  # is that it's at least 12 characters long.
  keySeed: "tz#C)z,DdiT,ng)sA+mPQy#GjgwKrDgtp8.n7HdA_z!+0YJZHrLrT?!N>fuMm1L)2ru@#*7*Qq*m>B#arf^=>z}7LCA_VuWMiTin"

  tz: "Asia/Shanghai"


resources:
   limits:
     cpu: 1000m
     memory: 128Mi
   requests:
     cpu: 10m
   memory: 128Mi


securityContext:
  runAsUser: 0

