lldap:
  replicaCount: 1

  image:
    repository: lldap/lldap
    tag: stable-alpine-rootless
    pullPolicy: IfNotPresent

  env:
    TZ: UTC
    UID: "1000"
    GID: "1000"
    LDAPS_OPTIONS__ENABLED: false

  extraEnv:
    - name: LLDAP_DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: lldap-secrets
          key: database-url
    - name: LLDAP_HTTP_URL
      value: http://localhost:17170

  persistence:
    enabled: false

  hpa:
    enabled: false

  service:
    type: ClusterIP

  ingress:
    enabled: false

  certmanager:
    enabled: false

  serviceAccount:
    create: false

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  secret:
    create: false
    name: lldap-secrets
    useExisting: true
