apiVersion: v1
kind: Service
metadata:
  name: redpanda-service
  namespace: redpanda

spec:
  selector:
    app: redpanda
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: "9092"
    - protocol: TCP
      port: 33333
      targetPort: 33333
      name: "33333"
    - protocol: TCP
      port: 33145
      targetPort: 33145
      name: "33145"

  clusterIP: None