dashboard:
  enabled: false

controlPlane:
  controlPlane:
    extraConfig:
      deployment:
        role: traditional
        role_traditional:
          config_provider: etcd
    service:
      extraPorts:
        - name: http
          port: 80
          targetPort: 9080
        - name: https
          port: 443
          targetPort: 9443
  resources:
    requests:
      cpu: 10m
      ephemeral-storage: 50Mi
      memory: 256Mi
    limits:
      cpu: 1000m
      ephemeral-storage: 2Gi
      memory: 1024Mi

dataPlane:
  enabled: false
#  containerPorts:
#    http: 80
#    https: 443
  resources:
    requests:
      cpu: 10m
      ephemeral-storage: 50Mi
      memory: 100Mi
    limits:
      cpu: 1000m
      ephemeral-storage: 2Gi
      memory: 1024Mi

ingressController:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 512Mi

etcd:
  enabled: true
  resources:
    limits:
      cpu: 500m
      ephemeral-storage: 2Gi
      memory: 500Mi
    requests:
      cpu: 10m
      ephemeral-storage: 50Mi
      memory: 256Mi