global:
  imageRegistry: "registry.cn-shenzhen.aliyuncs.com"

config:
  organization:
    name: "mail@acitrus.cn"
  admin:
    email: "mail@acitrus.cn"
    password: "mail@acitrus.cn"
  database:
    host: "postgresql.default"
    port: 5432
    name: "conduktor"
    password: "component"
    username: "root"
  clusters:
    - id: 'kafka-default'
      name: 'kafka-default'
      bootstrapServers: 'kafka.default:9092'
      icon: kafka
      properties: |
        security.protocol=SASL_PLAINTEXT
        sasl.mechanism=PLAIN
        sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='kafka' password='QHZTQCVTN3A2JXlXaCEmaU1AYjBTZyRuSEImMmU3UE0=';

platform:
  image:
    registry: registry.cn-shenzhen.aliyuncs.com
    repository: gravitation/conduktor-console
    tag: 1.26.0
  resources:
    limits:
      cpu: 3000m
      memory: 4Gi
    requests:
      cpu: 10m
      memory: 1Gi
  extraEnvVars:
    - name: RUN_MODE
      value: "custom"
    - name: CONSOLE_MEMORY_OPTS
      value: "-XX:+UseContainerSupport -Xmx1700m -Xshareclasses:cacheDir=/tmp/javasharedresources,name=cache -Xtune:virtualized -Xquickstart"
    - name: GOVERNANCE_MEMORY_OPTS
      value: "-XX:+UseContainerSupport -Xmx512m -Xshareclasses:cacheDir=/tmp/javasharedresources,name=cache -Xtune:virtualized -Xquickstart"
    - name: AUTHENTICATOR_MEMORY_OPTS
      value: "-XX:+UseContainerSupport -Xmx128m -Xshareclasses:cacheDir=/tmp/javasharedresources,name=cache -Xtune:virtualized -Xquickstart"
platformCortex:
  image:
    registry: registry.cn-shenzhen.aliyuncs.com
    repository: gravitation/conduktor-console-cortex
    tag: 1.25.1
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 100Mi