postgresqlIngress:
  enabled: true
  name: postgresql-ingress-route-tcp
  host: postgresql.tcp.acitrus.cn
  entryPoints:
    - gravitation
  service:
    name: postgresql
    port: 5432
  tls:
    domains:
      - main: acitrus.cn
        sans:
          - postgresql.tcp.acitrus.cn

postgresql:
  architecture: standalone
  primary:
    extraEnvVars:
      - name: TZ
        value: "Asia/Shanghai"
    persistence:
      size: 10Gi
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 10m
        memory: 128Mi
