postgresql:
  architecture: standalone
  primary:
    extraEnvVars:
      - name: TZ
        value: "Asia/Shanghai"
    persistence:
      size: 1Gi
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 10m
        memory: 128Mi
