# 版本信息
apiVersion: apps/v1

# 类型
kind: StatefulSet

# 元数据
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore

spec:


  # ----------------- 1.多副本策略 -----------------
  replicas: 1
  # 滚动更新
  updateStrategy:
    type: RollingUpdate
  # 最短就绪时间
  minReadySeconds: 10
  # ----------------- 1.多副本策略 -----------------

  serviceName: hive-metastore-service

  # 选择器
  selector:
    matchLabels:
      # 必须匹配 .spec.template.metadata.labels
      app: hive-metastore




  # 模版信息
  template:
    metadata:
      name: hive-metastore
      # 必须匹配 .spec.selector.matchLabels
      labels:
        app: hive-metastore

    spec:
      containers:
        - name: hive-metastore
          image: wfybelief/hive:dev
          imagePullPolicy: IfNotPresent

          # 资源限制
          resources:
            limits:
              # 1024 / 3
              memory: 2048Mi
              cpu: 500m
            requests:
              cpu: 1m
              memory: 10Mi

#          ports:
#            - containerPort: 2181
#              protocol: TCP

          # 存活监测
          #          livenessProbe:
          #            tcpSocket:
          #              port: 2180
          #            initialDelaySeconds: 30
          #            periodSeconds: 10

          volumeMounts:
            - mountPath: /opt/component/hive/conf/hive-site.xml
              subPath: hive-site.xml
              name: hive-metastore-conf
              readOnly: true
            - mountPath: /opt/component/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
              name: hive-metastore-conf
              readOnly: true
            - mountPath: /opt/component/hadoop/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
              name: hive-metastore-conf
              readOnly: true
            - mountPath: /opt/component/hadoop/etc/hadoop/mapred-site.xml
              subPath: mapred-site.xml
              name: hive-metastore-conf
              readOnly: true
            - mountPath: /opt/component/hadoop/etc/hadoop/yarn-site.xml
              subPath: yarn-site.xml
              name: hive-metastore-conf
              readOnly: true

      volumes:
        - name: hive-metastore-conf
          configMap:
            name: hive-metastore-configmap
            items:
              - key: hive-site.xml
                path: hive-site.xml
              - key: core-site.xml
                path: core-site.xml
              - key: hdfs-site.xml
                path: hdfs-site.xml
              - key: mapred-site.xml
                path: mapred-site.xml
              - key: yarn-site.xml
                path: yarn-site.xml

      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore-service
  labels:
    app: hive-metastore-service
spec:
#  ports:
#    - port: 2181
#      name: client
#      targetPort: 2181
#      protocol: TCP

  clusterIP: None
  selector:
    app: hive-metastore

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-configmap
data:
  hive-site.xml: |
    <configuration>
        <!-- Hive产生的元数据存放位置-->
        <property>
            <name>hive.metastore.warehouse.dir</name>
            <value>hdfs://namenode-service:8020/user/hive/warehouse</value>
        </property>
        <!-- 数据库连接JDBC的URL地址-->
        <property>
            <name>javax.jdo.option.ConnectionURL</name>
            <value>jdbc:postgresql://postgres-service:5432/hive_metastore?createDatabaseIfNotExist=true&amp;useSSL=false&amp;allowPublicKeyRetrieval=true</value>
        </property>
        <!-- 数据库连接driver，即MySQL驱动-->
        <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            <value>org.postgresql.Driver</value>
        </property>
        <!-- MySQL数据库用户名-->
        <property>
            <name>javax.jdo.option.ConnectionUserName</name>
            <value>root</value>
        </property>
        <!-- MySQL数据库密码-->
        <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            <value>component</value>
        </property>
        <!-- 暂时注释 
        <property>
            <name>hive.metastore.schema.verification</name>
            <value>false</value>
        </property>
        <property>
            <name>datanucleus.schema.autoCreateAll</name>
            <value>true</value>
        </property>
        使用本地服务连接Hive,默认为true
        <property>
            <name>hive.metastore.local</name>
            <value>false</value>
        </property>
        连接服务器
        <property>
            <name>hive.metastore.uris</name>
            <value>thrift://localhost:9083</value>
        </property>
        -->
    </configuration>

  core-site.xml: |
    <configuration>
        <property>
            <name>fs.defaultFS</name>
            <value>hdfs://namenode-service</value>
        </property>
    </configuration>
  hdfs-site.xml: |
    <configuration>
        <property>
            <name>dfs.replication</name>
            <value>2</value>
        </property>
    </configuration>
  mapred-site.xml: |
    <configuration>
        <property>
            <!--指定Mapreduce运行在yarn上-->
            <name>mapreduce.framework.name</name>
            <value>yarn</value>
        </property>
        <property>
            <name>yarn.app.mapreduce.am.env</name>
            <value>HADOOP_MAPRED_HOME=${HADOOP_HOME}</value>
        </property>
        <property>
            <name>mapreduce.map.env</name>
            <value>HADOOP_MAPRED_HOME=${HADOOP_HOME}</value>
        </property>
        <property>
            <name>mapreduce.reduce.env</name>
            <value>HADOOP_MAPRED_HOME=${HADOOP_HOME}</value>
        </property>
        <property>
            <name>mapreduce.map.memory.mb</name>
            <value>1024</value>
        </property>
        <property>
            <name>mapreduce.map.java.opts</name>
            <value>-Xms819m -Xmx819m</value>
        </property>
        <property>
            <name>mapreduce.reduce.memory.mb</name>
            <value>2048</value>
        </property>
        <property>
            <name>mapreduce.reduce.java.opts</name>
            <value>-Xms1638m -Xmx1638m</value>
        </property>
    </configuration>
  yarn-site.xml: |
    <configuration>
        <property>
            <name>yarn.nodemanager.aux-services</name>
            <value>mapreduce_shuffle</value>
        </property>

        <property>
            <name>yarn.resourcemanager.hostname</name>
            <value>resourcemanager-service</value>
        </property>

        <property>
            <name>yarn.scheduler.minimum-allocation-mb</name>
            <value>1024</value>
        </property>

        <property>
            <name>yarn.scheduler.maximum-allocation-mb</name>
            <value>3072</value>
        </property>

        <property>
            <name>yarn.app.mapreduce.am.resource.mb</name>
            <value>2048</value>
        </property>
        
        <property>
            <name>arn.app.mapreduce.am.command-opts</name>
            <value>-Xms1638m -Xmx1638m</value>
        </property>
        
        <property>
            <name>yarn.nodemanager.resource.memory-mb</name>
            <value>3072</value>
        </property>

        <property>
            <name>yarn.resourcemanager.address</name>
            <value>resourcemanager-service</value>
        </property>

        <property>
            <name>yarn.resourcemanager.scheduler.address</name>
            <value>resourcemanager-service</value>
        </property>

        <property>
            <name>yarn.resourcemanager.resource-tracker.address</name>
            <value>resourcemanager-service</value>
        </property>

    </configuration>