# 版本信息
apiVersion: apps/v1

# 类型
kind: StatefulSet

# 元数据
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore

spec:


  # ----------------- 1.多副本策略 -----------------
  replicas: 1
  # 滚动更新
  updateStrategy:
    type: RollingUpdate
  # 最短就绪时间
  minReadySeconds: 10
  # ----------------- 1.多副本策略 -----------------

  serviceName: hive-metastore-service

  # 选择器
  selector:
    matchLabels:
      # 必须匹配 .spec.template.metadata.labels
      app: hive-metastore




  # 模版信息
  template:
    metadata:
      name: hive-metastore
      # 必须匹配 .spec.selector.matchLabels
      labels:
        app: hive-metastore

    spec:
      containers:
        - name: hive-metastore
          image: wfybelief/zookeeper:main
          imagePullPolicy: IfNotPresent

          # 资源限制
          resources:
            limits:
              # 1024 / 3
              memory: 2048Mi
              cpu: 500m
            requests:
              cpu: 1m
              memory: 10Mi

          ports:
            - containerPort: 2181
              protocol: TCP

          # 存活监测
          #          livenessProbe:
          #            tcpSocket:
          #              port: 2180
          #            initialDelaySeconds: 30
          #            periodSeconds: 10

          volumeMounts:
            - mountPath: /opt/component/zookeeper/conf/zoo_sample.cfg
              subPath: zoo_sample.cfg
              name: zookeeper-conf
              readOnly: false

      volumes:
        - name: hive-metastore-conf
          configMap:
            name: hive-metastore-configmap
            items:
              - key: zoo_sample.cfg
                path: zoo_sample.cfg

      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore-service
  labels:
    app: hive-metastore-service
spec:
  ports:
    - port: 2181
      name: client
      targetPort: 2181
      protocol: TCP

  clusterIP: None
  selector:
    app: hive-metastore

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-configmap
data:
  zoo_sample.cfg: |
    # The number of milliseconds of each tick
    tickTime=2000
    # The number of ticks that the initial
    # synchronization phase can take
    initLimit=10
    # The number of ticks that can pass between
    # sending a request and getting an acknowledgement
    syncLimit=5
    # the directory where the snapshot is stored.
    # do not use /tmp for storage, /tmp here is just
    # example sakes.
    dataDir=/opt/component/storage/data
    dataLogDir=/opt/component/storage/log
    # the port at which the clients will connect
    clientPort=2181
    # the maximum number of client connections.
    # increase this if you need to handle more clients
    #maxClientCnxns=60
    #
    # Be sure to read the maintenance section of the
    # administrator guide before turning on autopurge.
    #
    # https://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_maintenance
    #
    # The number of snapshots to retain in dataDir
    #autopurge.snapRetainCount=3
    # Purge task interval in hours
    # Set to "0" to disable auto purge feature
    #autopurge.purgeInterval=1
    
    ## Metrics Providers
    #
    # https://prometheus.io Metrics Exporter
    #metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider
    #metricsProvider.httpHost=0.0.0.0
    #metricsProvider.httpPort=7000
    #metricsProvider.exportJvmInfo=true    
