# https://airflow.apache.org/docs/helm-chart/stable/production-guide.html#database
postgresql:
  enabled: false


# https://airflow.apache.org/docs/helm-chart/1.7.0/production-guide.html#pgbouncer
pgbouncer:
  enabled: true
  # The maximum number of connections to PgBouncer
  # maxClientConn: 100
  # The maximum number of server connections to the metadata database from PgBouncer
  metadataPoolSize: 5
  # The maximum number of server connections to the result backend database from PgBouncer
  resultBackendPoolSize: 3

# k3s
# https://airflow.apache.org/docs/helm-chart/stable/index.html#installing-the-chart-with-argo-cd-flux-rancher-or-terraform
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false

# https://stackoverflow.com/questions/78145304/deploy-airflow-with-helm-chart-pods-stuck-on-wait-for-airflow-migration
#scheduler:
#  waitForMigrations:
#    enabled: false
#
#_rpcServer:
#  waitForMigrations:
#    enabled: false
#
#webserver:
#  waitForMigrations:
#    enabled: false
#
#workers:
#  waitForMigrations:
#    enabled: false
#
#triggerer:
#  waitForMigrations:
#    enabled: false
#
#dagProcessor:
#  waitForMigrations:
#    enabled: false

