# https://airflow.apache.org/docs/helm-chart/stable/production-guide.html#database
postgresql:
  enabled: false


# https://airflow.apache.org/docs/helm-chart/1.7.0/production-guide.html#pgbouncer
pgbouncer:
  enabled: true
  # The maximum number of connections to PgBouncer
  # maxClientConn: 100
  # The maximum number of server connections to the metadata database from PgBouncer
  metadataPoolSize: 5
  # The maximum number of server connections to the result backend database from PgBouncer
  resultBackendPoolSize: 3

# k3s
# https://airflow.apache.org/docs/helm-chart/stable/index.html#installing-the-chart-with-argo-cd-flux-rancher-or-terraform
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false

# https://stackoverflow.com/questions/78145304/deploy-airflow-with-helm-chart-pods-stuck-on-wait-for-airflow-migration
#scheduler:
#  waitForMigrations:
#    enabled: false
#
#_rpcServer:
#  waitForMigrations:
#    enabled: false
#
#webserver:
#  waitForMigrations:
#    enabled: false
#
#workers:
#  waitForMigrations:
#    enabled: false
#
#triggerer:
#  waitForMigrations:
#    enabled: false
#
#dagProcessor:
#  waitForMigrations:
#    enabled: false

webserver:
  webserverConfig: |
    from airflow.providers.fab.auth_manager.security_manager.override import FabAirflowSecurityManagerOverride
    from flask_appbuilder.security.manager import AUTH_OAUTH
    import os

    AUTH_TYPE = AUTH_OAUTH
    AUTH_ROLES_SYNC_AT_LOGIN = True  # Checks roles on every login
    AUTH_USER_REGISTRATION = True  # allow users who are not already in the FAB DB to register

    AUTH_ROLES_MAPPING = {
        "Viewer": ["Viewer"],
        "Admin": ["Admin"],
    }
    # If you wish, you can add multiple OAuth providers.
    OAUTH_PROVIDERS = [
        {
            "name": "github",
            "icon": "fa-github",
            "token_key": "access_token",
            "remote_app": {
                "client_id": os.getenv("OAUTH_APP_ID"),
                "client_secret": os.getenv("OAUTH_APP_SECRET"),
                "api_base_url": "https://api.github.com",
                "client_kwargs": {"scope": "read:user, read:org"},
                "access_token_url": "https://github.com/login/oauth/access_token",
                "authorize_url": "https://github.com/login/oauth/authorize",
                "request_token_url": None,
            },
        },
    ]


    class CustomSecurityManager(FabAirflowSecurityManagerOverride):
        pass


    # Make sure to replace this with your own implementation of AirflowSecurityManager class
    SECURITY_MANAGER_CLASS = CustomSecurityManager