global:
  imageRegistry: "registry.cn-shenzhen.aliyuncs.com"

platform:
  image:
    registry: registry.cn-shenzhen.aliyuncs.com
    repository: gravitation/conduktor-console
  resources:
    limits:
      cpu: 3000m
      memory: 4Gi
    requests:
      cpu: 10m
      memory: 1Gi
  extraEnvVars:
    - name: TZ
      value: "Asia/Shanghai"

platformCortex:
  image:
    registry: registry.cn-shenzhen.aliyuncs.com
    repository: gravitation/conduktor-console-cortex
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 100Mi
  extraEnvVars:
    - name: TZ
      value: "Asia/Shanghai"