apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: redpanda
    meta.helm.sh/release-namespace: redpanda
  creationTimestamp: "2024-07-23T14:47:51Z"
  generation: 1
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.8.12
  name: redpanda
  namespace: redpanda
  resourceVersion: "3646"
  uid: c87ce402-576b-4d94-ad85-7366172ab3cf
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: redpanda-statefulset
      app.kubernetes.io/instance: redpanda
      app.kubernetes.io/name: redpanda
  serviceName: redpanda
  template:
    metadata:
      annotations:
        config.redpanda.com/checksum: 46b9b4bd856dbf13eaf798c3c27dac7d5f30eba24d7d0cabb536567372e4b1c9
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: redpanda-statefulset
        app.kubernetes.io/instance: redpanda
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: redpanda
        helm.sh/chart: redpanda-5.8.12
        redpanda.com/poddisruptionbudget: redpanda
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: redpanda-statefulset
                app.kubernetes.io/instance: redpanda
                app.kubernetes.io/name: redpanda
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - rpk
        - redpanda
        - start
        - --advertise-rpc-addr=$(SERVICE_NAME).redpanda.redpanda.svc.cluster.local.:33145
        env:
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: docker.redpanda.com/redpandadata/redpanda:v24.1.8
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                timeout -v 45 bash -x /var/lifecycle/postStart.sh
                true
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                timeout -v 45 bash -x /var/lifecycle/preStop.sh
                true # do not fail and cause the pod to terminate
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl --silent --fail -k -m 5 --cacert /etc/tls/certs/default/ca.crt
              "https://${SERVICE_NAME}.redpanda.redpanda.svc.cluster.local.:9644/v1/status/ready"
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: redpanda
        ports:
        - containerPort: 9644
          name: admin
          protocol: TCP
        - containerPort: 9645
          name: admin-default
          protocol: TCP
        - containerPort: 8082
          name: http
          protocol: TCP
        - containerPort: 8083
          name: http-default
          protocol: TCP
        - containerPort: 9093
          name: kafka
          protocol: TCP
        - containerPort: 9094
          name: kafka-default
          protocol: TCP
        - containerPort: 33145
          name: rpc
          protocol: TCP
        - containerPort: 8081
          name: schemaregistry
          protocol: TCP
        - containerPort: 8084
          name: schema-default
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              set -x
              RESULT=$(rpk cluster health)
              echo $RESULT
              echo $RESULT | grep 'Healthy:.*true'
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 2560Mi
        securityContext:
          runAsGroup: 101
          runAsUser: 101
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              set -e
              RESULT=$(curl --silent --fail -k -m 5 --cacert /etc/tls/certs/default/ca.crt "https://${SERVICE_NAME}.redpanda.redpanda.svc.cluster.local.:9644/v1/status/ready")
              echo $RESULT
              echo $RESULT | grep ready
          failureThreshold: 120
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tls/certs/default
          name: redpanda-default-cert
        - mountPath: /etc/tls/certs/external
          name: redpanda-external-cert
        - mountPath: /etc/redpanda
          name: config
        - mountPath: /tmp/base-config
          name: redpanda
        - mountPath: /var/lifecycle
          name: lifecycle-scripts
        - mountPath: /var/lib/redpanda/data
          name: datadir
        - mountPath: /etc/redpanda-io-config
          name: redpanda-io-config
      - args:
        - -c
        - trap "exit 0" TERM; exec /etc/secrets/config-watcher/scripts/sasl-user.sh
          & wait $!
        command:
        - /bin/sh
        image: docker.redpanda.com/redpandadata/redpanda:v24.1.8
        imagePullPolicy: IfNotPresent
        name: config-watcher
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tls/certs/default
          name: redpanda-default-cert
        - mountPath: /etc/tls/certs/external
          name: redpanda-external-cert
        - mountPath: /etc/redpanda
          name: config
        - mountPath: /etc/secrets/config-watcher/scripts
          name: redpanda-config-watcher
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /bin/bash
        - -c
        - rpk redpanda tune all
        image: docker.redpanda.com/redpandadata/redpanda:v24.1.8
        imagePullPolicy: IfNotPresent
        name: tuning
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_RESOURCE
          privileged: true
          runAsGroup: 0
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tls/certs/default
          name: redpanda-default-cert
        - mountPath: /etc/tls/certs/external
          name: redpanda-external-cert
        - mountPath: /etc/redpanda
          name: redpanda
      - command:
        - /bin/bash
        - -c
        - trap "exit 0" TERM; exec $CONFIGURATOR_SCRIPT "${SERVICE_NAME}" "${KUBERNETES_NODE_NAME}"
          & wait $!
        env:
        - name: CONFIGURATOR_SCRIPT
          value: /etc/secrets/configurator/scripts/configurator.sh
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: HOST_IP_ADDRESS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: docker.redpanda.com/redpandadata/redpanda:v24.1.8
        imagePullPolicy: IfNotPresent
        name: redpanda-configurator
        resources: {}
        securityContext:
          runAsGroup: 101
          runAsUser: 101
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tls/certs/default
          name: redpanda-default-cert
        - mountPath: /etc/tls/certs/external
          name: redpanda-external-cert
        - mountPath: /etc/redpanda
          name: config
        - mountPath: /tmp/base-config
          name: redpanda
        - mountPath: /etc/secrets/configurator/scripts/
          name: redpanda-configurator
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 90
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: redpanda-statefulset
            app.kubernetes.io/instance: redpanda
            app.kubernetes.io/name: redpanda
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - name: redpanda-default-cert
        secret:
          defaultMode: 288
          secretName: redpanda-default-cert
      - name: redpanda-external-cert
        secret:
          defaultMode: 288
          secretName: redpanda-external-cert
      - name: lifecycle-scripts
        secret:
          defaultMode: 509
          secretName: redpanda-sts-lifecycle
      - configMap:
          defaultMode: 420
          name: redpanda
        name: redpanda
      - emptyDir: {}
        name: config
      - name: redpanda-configurator
        secret:
          defaultMode: 509
          secretName: redpanda-configurator
      - name: redpanda-config-watcher
        secret:
          defaultMode: 509
          secretName: redpanda-config-watcher
      - name: redpanda-fs-validator
        secret:
          defaultMode: 509
          secretName: redpanda-fs-validator
      - configMap:
          defaultMode: 420
          name: redpanda-io-config
        name: redpanda-io-config
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: redpanda
        app.kubernetes.io/instance: redpanda
        app.kubernetes.io/name: redpanda
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 0
  collisionCount: 0
  currentReplicas: 3
  currentRevision: redpanda-ff69999b7
  observedGeneration: 1
  replicas: 3
  updateRevision: redpanda-ff69999b7
  updatedReplicas: 3