apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cloud-agent
  labels:
    app: cloud-agent
  namespace: data-asset-platform-test

spec:
  serviceName: cloud-agent-service
  replicas: 1
  selector:
    matchLabels:
      app: cloud-agent
  template:
    metadata:
      name: cloud-agent
      labels:
        app: cloud-agent
    spec:
      containers:
        - name: cloud-agent
          image: registry.cn-shenzhen.aliyuncs.com/acitrus/teamcity:agent-2024-05-26
          imagePullPolicy: IfNotPresent

          #          securityContext:
          #            allowPrivilegeEscalation: false
          #            runAsUser: 0
          env:
            - name: SERVER_URL
              value: https://public-pipeline.acitrus.cn

          resources:
            limits:
              # 1024 / 1
              memory: 2048Mi
              cpu: 4000m
            requests:
              memory: 100Mi
              cpu: 1m

          ports:
            - containerPort: 9090
              protocol: TCP

          volumeMounts:
            - mountPath: /data/teamcity_agent/conf
              name: component-storage
              readOnly: false

      restartPolicy: Always

  # 持久卷
  volumeClaimTemplates:
    - metadata:
        name: component-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: csi-disk-ssd # csi-disk-ssd | hostpath
        resources:
          requests:
            storage: 1Gi
          limits:
            storage: 1Gi