# 版本信息
apiVersion: apps/v1

# 类型
kind: StatefulSet

# 元数据
metadata:
  name: hive-server
  labels:
    app: hive-server

spec:


  # ----------------- 1.多副本策略 -----------------
  replicas: 1
  # 滚动更新
  updateStrategy:
    type: RollingUpdate
  # 最短就绪时间
  minReadySeconds: 10
  # ----------------- 1.多副本策略 -----------------

  serviceName: hive-server-service

  # 选择器
  selector:
    matchLabels:
      # 必须匹配 .spec.template.metadata.labels
      app: hive-server




  # 模版信息
  template:
    metadata:
      name: hive-server
      # 必须匹配 .spec.selector.matchLabels
      labels:
        app: hive-server

    spec:
      initContainers:
        - name: hadoop-resource-init
          image: wfybelief/hadoop:3.3.6
          imagePullPolicy: IfNotPresent
          command:
            - busybox
            - sh
            - -c
          args:
            - |
              tar -zxvf /opt/component/storage/hadoop/hadoop-*.tar.gz -C /opt/component/hadoop --strip-components 1
          volumeMounts:
            - mountPath: /opt/component/hadoop
              name: hadoop-resource-volume

        - name: tez-resource-init
          imagePullPolicy: IfNotPresent
          image: wfybelief/tez:tez_0.10.2_hadoop_3.3.4
          command:
            - busybox
            - sh
            - -c
          args:
            - |
              tar -zxvf /opt/component/storage/tez/tez-*[0-9].tar.gz -C /opt/component/tez/
              # tar -zxvf /opt/component/storage/tez/tez-*-minimal.tar.gz -C /opt/component/tez/
          volumeMounts:
            - mountPath: /opt/component/tez
              name: tez-resource-volume

        - name: hive-resource-init
          imagePullPolicy: IfNotPresent
          image: apache/hive:3.1.3
          command:
            - cp
          args:
            - -r
            - /opt/hive
            - /opt/component/
          volumeMounts:
            - mountPath: /opt/component/hive
              name: hive-resource-volume

        - name: driver-resource-init
          imagePullPolicy: IfNotPresent
          image: wfybelief/jdbc-driver:0.0.1
          command:
            - sh
            - -c
          args:
            - |
              cp /opt/component/storage/jdbc/driver/postgres/postgresql-*.jar /opt/component/hive/lib/
          volumeMounts:
            - mountPath: /opt/component/hive
              name: hive-resource-volume

      containers:
        - name: hive-server
          image: wfybelief/jdk-8:0.0.4
          imagePullPolicy: IfNotPresent
          command:
            - busybox
            - sh
            - entrypoint.sh
          args:
            - hive
            - --service
            - hiveserver2
          env:
            - name: HIVE_SERVER2_HADOOP_OPTS
              value: -XX:+UseContainerSupport
                -XX:InitialRAMPercentage=50.0
                -XX:MaxRAMPercentage=50.0
                -Xshareclasses
                -Xtune:virtualized
                -Xquickstart

            - name: HADOOP_HEAPSIZE
              value: '1536'

          # 资源限制
          resources:
            limits:
              # 1024 / 3
              memory: 3072Mi
              cpu: 4000m
            requests:
              cpu: 1m
              memory: 10Mi

          volumeMounts:
            # hive配置持久卷
            - name: hive-config-volume
              mountPath: /opt/component/hive/conf/hive-site.xml
              subPath: hive-site.xml
              readOnly: true

            - name: hive-config-volume
              mountPath: /opt/component/hive/conf/hive-env.sh
              readOnly: true
              subPath: hive-env.sh

            - name: hive-config-volume
              mountPath: /opt/component/tez/conf/tez-site.xml
              readOnly: true
              subPath: tez-site.xml

            - name: hive-config-volume
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
              readOnly: true

            # 资源拷贝持久卷
            - name: hadoop-resource-volume
              mountPath: /opt/component/hadoop

            - name: hive-resource-volume
              mountPath: /opt/component/hive

            - name: tez-resource-volume
              mountPath: /opt/component/tez

            # hadoop配置持久卷
            - mountPath: /opt/component/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
              name: hadoop-config-volume
              readOnly: true

            - mountPath: /opt/component/hadoop/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
              name: hadoop-config-volume
              readOnly: true

            - mountPath: /opt/component/hadoop/etc/hadoop/mapred-site.xml
              subPath: mapred-site.xml
              name: hadoop-config-volume
              readOnly: true

            - mountPath: /opt/component/hadoop/etc/hadoop/yarn-site.xml
              subPath: yarn-site.xml
              name: hadoop-config-volume
              readOnly: true

      volumes:
        - name: hadoop-config-volume
          configMap:
            name: hadoop-configmap

            items:
              - key: core-site.xml
                path: core-site.xml

              - key: hdfs-site.xml
                path: hdfs-site.xml

              - key: mapred-site.xml
                path: mapred-site.xml

              - key: yarn-site.xml
                path: yarn-site.xml

        - name: hive-config-volume
          configMap:
            name: hive-configmap

            items:
              - key: entrypoint.sh
                path: entrypoint.sh

              - key: hive-env.sh
                path: hive-env.sh

              - key: hive-site.xml
                path: hive-site.xml
              - key: tez-site.xml
                path: tez-site.xml

        - name: hadoop-resource-volume
          emptyDir: { }
        - name: hive-resource-volume
          emptyDir: { }
        - name: tez-resource-volume
          emptyDir: { }

      restartPolicy: Always


