apiVersion: batch/v1
kind: CronJob
metadata:
  name: ssl-certificate
  labels:
    app: ssl-certificate

spec:
  schedule: "*/30 * * * *" #	Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ssl-certificate
              image: ubuntu:24.04
              imagePullPolicy: IfNotPresent
              command:
                - top
                - -b
          restartPolicy: OnFailure

