installCRDs: true
controller:
  image:
    registry: registry.cn-shenzhen.aliyuncs.com
    repository: gravitation/cert-manager
    tag: 1.15.2-debian-12-r1
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
webhook:
  image:
    registry: registry.cn-shenzhen.aliyuncs.com
    repository: gravitation/cert-manager-webhook
    tag: 1.15.2-debian-12-r1
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
cainjector:
  image:
    registry: registry.cn-shenzhen.aliyuncs.com
    repository: gravitation/cainjector
    tag: 1.15.2-debian-12-r1
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 1024Mi