# 第一阶段编译脚本文件
FROM python:3.10.8-slim-bullseye as python

# 元数据
LABEL MAINTAINER="wfy"

# 变量定义区域
ARG  PYTHON_BUILD_PATH=/opt/python/builder/
ARG  PYTHON_BUILD_NAME=builder

# 前置环境准备
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y binutils && \
    pip install pyinstaller ujson

# 拉取文件
ADD ./$PYTHON_BUILD_NAME.py $PYTHON_BUILD_PATH

# 编译二进制
RUN pyinstaller -F $PYTHON_BUILD_PATH/$PYTHON_BUILD_NAME.py

# 第二阶段搬运Hadoop（默认镜像不满足）
FROM  apache/hadoop:2 as hadoop


# 第三阶段jdk
FROM  openjdk:8 as java

USER root

# 时区
ENV TZ=Asia/Shanghai
ENV HADOOP_HOME=/opt/hadoop
ENV PATH=$PATH:$HADOOP_HOME/bin

# 复制本地文件
ADD ./* /opt/hadoop/docker/
WORKDIR /opt/hadoop/docker

# 复制其他镜像文件
COPY --from=python $PYTHON_BUILD_PATH/dist/$PYTHON_BUILD_NAME ./
COPY --from=hadoop /opt/hadoop /opt/hadoop

# 权限
RUN chmod +x ./entrypoint.sh

# 运行
ENTRYPOINT ["./entrypoint.sh"]
CMD [""]
