version: "3.9"
services:
  hadoop:
    build:
      dockerfile: DockerFile
    configs:
      - source: core-site
        target: /opt/hadoop/etc/hadoop/core-site.xml
        mode: 0440
      - source: hdfs-site
        target: /opt/hadoop/etc/hadoop/hdfs-site.xml
        mode: 0440
      - source: mapred-site
        target: /opt/hadoop/etc/hadoop/mapred-site.xml
        mode: 0440
      - source: yarn-site
        target: /opt/hadoop/etc/hadoop/yarn-site.xml
        mode: 0440
      - source: master
        target: /opt/hadoop/etc/hadoop/master
        mode: 0440
    image: wfybelief/component:hadoop
    env_file:
      - .env
    environment:
      - sys_t1=${ZOOKEEPER_REPLICAS:-1}
      - COMPOSE_SERVICE_NAME=hadoop
    networks:
      - component-network

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 800M
        reservations:
          cpus: "0.1"
          memory: 50M
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5



networks:
  component-network:
    external: false
    name: component-network
    labels:
      - "key=value"

configs:
  core-site:
    name: "core-site.xml"
    file: config/core-site.xml
  hdfs-site:
    name: "hdfs-site.xml"
    file: config/hdfs-site.xml
  mapred-site:
    name: "mapred-site.xml"
    file: config/mapred-site.xml
  yarn-site:
    name: "yarn-site.xml"
    file: config/yarn-site.xml
  master:
    name: "master"
    file: config/master

