apiVersion: v2
name: redis
description: Wrapper chart for Bitnami Redis with local values and extra resources
type: application
version: 0.1.0
appVersion: "7.2"
dependencies:
  - name: redis
    version: 19.6.4
    repository: https://charts.bitnami.com/bitnami
