apiVersion: v2
name: redis
description: Wrapper chart for Bitnami Redis with local values and extra resources
type: application
version: 0.1.0
appVersion: "8.2.1"
dependencies:
  - name: redis
    version: 23.1.1
    repository: https://charts.bitnami.com/bitnami
