redisIngress:
  enabled: true
  name: redis-ingress-route-tcp
  host: redis.acitrus.cn
  entryPoints:
    - gravitation
  service:
    name: redis-master
    port: 6379
  tls:
    domains:
      - main: acitrus.cn
        sans:
          - redis.acitrus.cn

redis:
  architecture: standalone
  master:
    extraEnvVars:
      - name: TZ
        value: "Asia/Shanghai"
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
