{{- if .Values.rustfsIngress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.rustfsIngress.console.name | quote }}
spec:
  entryPoints:
    {{- toYaml .Values.rustfsIngress.console.entryPoints | nindent 4 }}
  routes:
    - match: '{{ include "rustfs-wrapper.hostRule" . }}'
      services:
        - name: {{ include "rustfs-wrapper.serviceName" . | quote }}
          port: {{ .Values.rustfsIngress.service.consolePort }}
  {{- with .Values.rustfsIngress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.rustfsIngress.api.name | quote }}
spec:
  entryPoints:
    {{- toYaml .Values.rustfsIngress.api.entryPoints | nindent 4 }}
  routes:
    - match: '{{ include "rustfs-wrapper.hostRule" . }}'
      services:
        - name: {{ include "rustfs-wrapper.serviceName" . | quote }}
          port: {{ .Values.rustfsIngress.service.apiPort }}
  {{- with .Values.rustfsIngress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
