apiVersion: v2
name: rabbitmq
description: Wrapper chart for Bitnami RabbitMQ with local values and extra resources
type: application
version: 0.1.0
appVersion: "4.1"
dependencies:
  - name: rabbitmq
    version: 16.0.14
    repository: https://charts.bitnami.com/bitnami
