resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

extraEnvVars:
  - name: TZ
    value: "Asia/Shanghai"

plugins: "rabbitmq_management rabbitmq_peer_discovery_k8s rabbitmq_auth_backend_oauth2"