resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

extraEnvVars:
  - name: TZ
    value: "Asia/Shanghai"

# rabbitmq_auth_backend_oauth2
extraPlugins: "rabbitmq_auth_backend_oauth2"

extraConfiguration: |
  auth_backends.1 = rabbit_auth_backend_oauth2
  management.oauth_disable_basic_auth = true
  management.oauth_enabled = true
  management.oauth_client_id = ef10af80f0eb791e762e
  management.oauth_client_secret = 00dc74f0fa372e4ca229f335c8adf8e2481139a2
  management.oauth_scopes = openid profile rabbitmq.tag:administrator
  management.oauth_provider_url = https://auth.acitrus.cn

#  auth_oauth2.resource_server_id = rabbitmq
#  auth_oauth2.issuer = https://auth.acitrus.cn
