rabbitmqIngress:
  enabled: true
  name: rabbitmq-ingress-route-tcp
  host: rabbitmq.acitrus.cn
  entryPoints:
    - gravitation
  service:
    name: rabbitmq
    port: 5672
  tls:
    domains:
      - main: acitrus.cn
        sans:
          - rabbitmq.acitrus.cn

rabbitmqUiIngress:
  enabled: true
  name: rabbitmqui-ingress-route-http
  host: rabbitmq.ui.acitrus.cn
  entryPoints:
    - web
    - websecure
  redirectToHttps:
    enabled: true
    name: rabbitmqui-redirect-https
    permanent: true
  service:
    name: rabbitmq
    port: 15672
  tls:
    domains:
      - main: acitrus.cn
        sans:
          - rabbitmq.ui.acitrus.cn

rabbitmq:
  replicaCount: 1
  extraEnvVars:
    - name: TZ
      value: "Asia/Shanghai"
  auth:
   username: admin
  # ingress:
  #   enabled: false
  #   hostname: rabbitmq.acitrus.cn
  #   path: /
  persistence:
    enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 256Mi
