apiVersion: v1
kind: Secret
metadata:
  name: alidns
  namespace: traefik
# type: kubernetes.io/basic-auth
stringData:
  ALICLOUD_ACCESS_KEY: ""
  ALICLOUD_SECRET_KEY: ""

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
# homepage