version: "3.9"
services:
  # 网络下节点的名称组成为镜像名字 + service + num
  cache:
    image: redis:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.10'
          memory: 20M
      replicas: 2
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: '120s'
    networks:
      - redis-network

networks:
  redis-network:
    external: false
    name: redis-net
    labels:
      - "sdf=2"