gateway:
#  image:
#    registry: registry.cn-shenzhen.aliyuncs.com
#    repository: gravitation/conduktor-gateway
#    tag: 3.3.0
  env:
    GATEWAY_ADVERTISED_HOST: kafka.acitrus.cn
  extraSecretEnvVars:
    - name: GATEWAY_ADVERTISED_HOST
      value: kafka.acitrus.cn
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: kafka.default:9092
#    - name: GATEWAY_ROUTING_MECHANISM
#      value: host
#    - name: GATEWAY_ADVERTISED_HOST_PREFIX
#      value: broker-
#    - name: GATEWAY_ADVERTISED_SNI_PORT
#      value: "9092"
#    - name: LOG4J2_IO_CONDUKTOR_PROXY_NETWORK_LEVEL
#      value: "debug"
#    - name: LOG4J2_IO_CONDUKTOR_PROXY_SERVICE_LEVEL
#      value: debug
#    - name: LOG4J2_IO_CONDUKTOR_UPSTREAM_THREAD_LEVEL
#      value: debug
#    - name: LOG4J2_IO_CONDUKTOR_PROXY_AUTHORIZATION_LEVEL
#      value: debug
#    - name: KAFKA_SASL_MECHANISM
#      value: PLAIN
#    - name: KAFKA_SECURITY_PROTOCOL
#      value: SASL_PLAINTEXT
#    - name: KAFKA_SASL_JAAS_CONFIG
#      value: "org.apache.kafka.common.security.plain.PlainLoginModule required username='kafka' password='QHZTQCVTN3A2JXlXaCEmaU1AYjBTZyRuSEImMmU3UE0=';"
#    - name: KAFKA_SASL_MECHANISM
#      value: PLAIN
#    - name: KAFKA_SECURITY_PROTOCOL
#      value: SASL_PLAINTEXT
#    - name: KAFKA_SASL_JAAS_CONFIG
#      value: "org.apache.kafka.common.security.plain.PlainLoginModule required username='kafka' password='QHZTQCVTN3A2JXlXaCEmaU1AYjBTZyRuSEImMmU3UE0=';"

service:
  external:
    enable: true
    type: LoadBalancer
