authelia:
  pod:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 256Mi

  configMap:
    access_control:
      default_policy: deny
      rules:
        - domain: ldap.acitrus.cn
          policy: one_factor
          subject:
            - group:lldap_admin

    authentication_backend:
      ldap:
        enabled: true
        implementation: lldap
        address: ldap://lldap.infra.svc.cluster.local:3890
        base_dn: dc=acitrus,dc=cn
        user: uid=authelia,ou=people,dc=acitrus,dc=cn

    session:
      cookies:
        - domain: acitrus.cn
          subdomain: auth
      redis:
        enabled: true
        deploy: false
        host: redis-master.infra.svc.cluster.local
        port: 6379
        database_index: 1

    storage:
      local:
        enabled: false
      postgres:
        enabled: true
        deploy: false
        address: tcp://postgresql.infra.svc.cluster.local:5432
        database: authelia
        schema: public
        username: postgres

  secret:
    existingSecret: authelia-secrets

databaseBootstrap:
  enabled: true
  host: postgresql.infra.svc.cluster.local
  database: authelia
  existingSecret: postgresql-auth

autheliaIngress:
  enabled: true
  host: auth.acitrus.cn
  entryPoints:
    - websecure
  tls:
    certResolver: leresolver

autheliaForwardAuth:
  enabled: true
  address: http://authelia.infra.svc.cluster.local/api/authz/forward-auth
