# .github/workflows/deploy.yml
name: airflow-deploy
on:
  push:
    tags:
      - airflow-*.*.*
    branches:
      - airflow-*.*.*
env:
  CHART_VERSION: 1.15.0

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

      - name: Generate kubeconfig
        run: |
          kubectl apply -k charts/airflow/workloads

      # https://github.com/marketplace/actions/helm-deploy
      - name: 'airflow'
        uses: vimeda/helm@v1.7.0
        with:
          release: 'airflow'
          namespace: 'airflow'
          repo: 'https://airflow.apache.org'
          repo-alias: apache-airflow
          token: '${{ github.token }}'
          chart: 'apache-airflow/airflow'
          chart-version: ${{ env.CHART_VERSION }}
          timeout: 30m0s
          values: |
            data:
              metadataConnection:
                user: '${{ secrets.DEFAULT_DATABASE_USERNAME }}'
                pass: '${{ secrets.DEFAULT_DATABASE_PASSWORD }}'
                protocol: postgresql
                host: '${{ secrets.DEFAULT_DATABASE_HOST }}'
                port: ${{ secrets.DEFAULT_DATABASE_PORT }}
                db: 'airflow'
            webserver:
              webserverConfig: |
                import os
                import jwt
                import requests
                import logging
                from base64 import b64decode
                from cryptography.hazmat.primitives import serialization
                from flask_appbuilder.security.manager import AUTH_DB, AUTH_OAUTH
                from airflow import configuration as conf
                from airflow.www.security import AirflowSecurityManager

                log = logging.getLogger(__name__)
                
                AUTH_TYPE = AUTH_OAUTH
                # AUTH_ROLES_SYNC_AT_LOGIN = True  # Checks roles on every login
                AUTH_USER_REGISTRATION = True  # allow users who are not already in the FAB DB to register
                AUTH_USER_REGISTRATION_ROLE = "Public"

                # If you wish, you can add multiple OAuth providers.
                OAUTH_PROVIDERS = [
                    {
                        "name": "auth.acitrus.cn",
                        "icon": "fa-hand-o-left",
                        "token_key": "access_token",
                        "remote_app": {
                            "client_id": "${{ secrets.DEFAULT_OAUTH2_ID }}",
                            "client_secret": "${{ secrets.DEFAULT_OAUTH2_SECRET }}",
                            "api_base_url": "https://auth.acitrus.cn",
                            "client_kwargs": {"scope": "profile email"},
                            "access_token_url": "https://auth.acitrus.cn/api/login/oauth/access_token",
                            "authorize_url": "https://auth.acitrus.cn/login/oauth/authorize",
                            "request_token_url": None,
                            "jwks_uri": "https://auth.acitrus.cn/.well-known/jwks",
                        },
                    },
                ]
              
                # https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/auth-manager/webserver-authentication.html#example-using-team-based-authorization-with-keycloak
                class CustomSecurityManager(AirflowSecurityManager):
                    def get_oauth_user_info(self, provider, response):
                        log.info("user info: {0}".format(response))
                        log.info("user info: {0}".format(provider))
                        if provider == "auth.acitrus.cn":
                            token = response["access_token"]
                            me = jwt.decode(token, "secret", algorithms=["HS256", "RS256"])

                            # Extract roles from resource access
                            realm_access = me.get("realm_access", {})
                            groups = realm_access.get("roles", [])

                            log.info("groups: {0}".format(groups))

                            if not groups:
                                groups = ["Viewer"]

                            userinfo = {
                                "username": me.get("name"),
                                "email": me.get("email"),
                                "first_name": me.get("given_name"),
                                "last_name": me.get("family_name"),
                                "role_keys": groups,
                            }

                            log.info("user info: {0}".format(userinfo))

                            return userinfo
                        else:
                            return {}


                # Make sure to replace this with your own implementation of AirflowSecurityManager class
                SECURITY_MANAGER_CLASS = CustomSecurityManager
          value-files: "charts/airflow/sample.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'