# .github/workflows/deploy.yml
name: airflow-deploy
on:
  push:
    tags:
      - airflow-*.*.*
    branches:
      - airflow-*.*.*
env:
  CHART_VERSION: 1.15.0

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

      - name: Generate kubeconfig
        run: |
          kubectl apply -k charts/airflow/workloads

      # https://github.com/marketplace/actions/helm-deploy
      - name: 'airflow'
        uses: vimeda/helm@v1.7.0
        with:
          release: 'airflow'
          namespace: 'airflow'
          repo: 'https://airflow.apache.org'
          repo-alias: apache-airflow
          token: '${{ github.token }}'
          chart: 'apache-airflow/airflow'
          chart-version: ${{ env.CHART_VERSION }}
          timeout: 30m0s
          values: |
            data:
              metadataConnection:
                user: '${{ secrets.DEFAULT_DATABASE_USERNAME }}'
                pass: '${{ secrets.DEFAULT_DATABASE_PASSWORD }}'
                protocol: postgresql
                host: '${{ secrets.DEFAULT_DATABASE_HOST }}'
                port: ${{ secrets.DEFAULT_DATABASE_PORT }}
                db: 'airflow'
            webserver:
              webserverConfig: |
                from airflow.providers.fab.auth_manager.security_manager.override import FabAirflowSecurityManagerOverride
                from flask_appbuilder.security.manager import AUTH_OAUTH
                import os

                AUTH_TYPE = AUTH_OAUTH
                AUTH_ROLES_SYNC_AT_LOGIN = True  # Checks roles on every login
                AUTH_USER_REGISTRATION = True  # allow users who are not already in the FAB DB to register

                AUTH_ROLES_MAPPING = {
                    "Viewer": ["Viewer"],
                    "Admin": ["Admin"],
                }

                # If you wish, you can add multiple OAuth providers.
                OAUTH_PROVIDERS = [
                    {
                        "name": "auth.acitrus.cn",
                        "icon": "fa-hand-o-left",
                        "token_key": "access_token",
                        "remote_app": {
                            "client_id": "${{ secrets.DEFAULT_OAUTH2_ID }}",
                            "client_secret": "${{ secrets.DEFAULT_OAUTH2_SECRET }}",
                            "api_base_url": "https://auth.acitrus.cn",
                            'client_kwargs':{
                                'scope': 'User.read email openid profile basic users name preferred_username upn',
                                # 该值设置为应用程序id
                                "resource": '${{ secrets.DEFAULT_OAUTH2_ID }}',
                            },
                            "access_token_url": "https://auth.acitrus.cn/api/login/oauth/access_token",
                            "authorize_url": "https://auth.acitrus.cn/login/oauth/authorize",
                            "request_token_url": None
                        },
                    },
                ]


                class CustomSecurityManager(FabAirflowSecurityManagerOverride):
                    pass


                # Make sure to replace this with your own implementation of AirflowSecurityManager class
                SECURITY_MANAGER_CLASS = CustomSecurityManager

          value-files: "charts/airflow/sample.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'