# .github/workflows/deploy.yml
name: apisix-deploy
on:
  push:
    tags:
      - apisix-*.*.*
    branches:
      - apisix-*.*.*

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4


      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

      # https://github.com/marketplace/actions/helm-deploy
      - name: 'apisix'
        uses: vimeda/helm@v1.7.0
        with:
          release: 'apisix'
          namespace: 'gateway'
          # https://github.com/apache/apisix-helm-chart/blob/master/docs/en/latest/apisix.md
          repo: https://charts.apiseven.com
          repo-alias: "apisix"
          chart: 'apisix/apisix'
          token: '${{ github.token }}'
          chart-version: 2.10.0
          value-files: "charts/apisix/sample.yaml"
          timeout: 30m0s
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      - name: Generate kubeconfig
        run: |
          kubectl apply -k charts/apisix/workloads