# .github/workflows/deploy.yml
name: authelia-deploy
on:
  push:
    tags:
      - authelia-*.*.*
    branches:
      - authelia-*.*.*

env:
  CHART_VERSION: 0.9.14

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

      - uses: azure/setup-helm@v4.2.0
        with:
          version: '3.16.4' # default is latest (stable)
        id: install

      # https://github.com/because-of-you/helm-deploy
      - name: 'authelia'
        # 镜像
        uses: because-of-you/helm-deploy@master
        with:
          release: 'authelia'
          namespace: 'default'
          chart: 'authelia/authelia'
          repo: "https://charts.authelia.com"
          repo-alias: "authelia"
          token: '${{ github.token }}'
          version: ${{ env.CHART_VERSION }}
          value-files: "charts/authelia/sample.yaml"
          values: |
            configMap:
              session:
                redis:
                  password:
                    value: '${{ secrets.DEFAULT_PASSWORD}}'
              storage:
                postgres:
                  enabled: true
                  address: 'tcp://${{ secrets.DEFAULT_DATABASE_HOST }}:${{ secrets.DEFAULT_DATABASE_PORT }}'
                  database: 'authelia'
                  schema: 'public'
                  username: '${{ secrets.DEFAULT_DATABASE_USERNAME }}'
                  password:
                    value: '${{ secrets.DEFAULT_DATABASE_PASSWORD }}'
              identity_providers:
                oidc:
                  jwks:
                    - key_id: ''
                      # https://www.authelia.com/configuration/identity-providers/openid-connect/provider/#key
                      key:
                        value: |
                          -----BEGIN PRIVATE KEY-----
                          MIISQwIBADANBgkqhkiG9w0BAQEFAASCEi0wghIpAgEAAoIEAQDe6xi98+ureJ4k
                          Mbuc9RmkOWbQej3wY5/vTU9DQGsk525HhW9I9zkG+QWWu+dddjJYOwiu3XMC8hN5
                          1/XjPhPpE7j9jNHFetMBrr33r3hhz4KdBZRGp6SxIJL7mMKCSBzsfjkEhAg+LMld
                          XioCeYeeBcJJd1hmfhXwg3K/8a3lO3fzYJGbRjRVdwY8pqudxo3iw+fJJwtWkfbd
                          R/YZ9yyGOfEajnU+9afFgKAHPJVVYjbW6MBEeJ5mAsViZ4YcuRxIuvIMSRNf3VS7
                          y8NxO0O57Ud3oPThogPUSl5f723gOYdEoRP1ndPU7UKKYADRhhhj1XY6epnD2200
                          4HXaMNEn0QmXTjbo4U2OhvZTPliwIDJV4VevKpDJdwHHRsKL1Pi8JSW9xCru16R4
                          nFepcZCJBFJdwCCUJD93+C+7eHjE0oHGG6mU1xyijhYjbwfm17IiF2w6YcDnHKWA
                          snhOAs6aQvwNSxXTy13AxkMzL2SKDeuviKHpY9Ldx0NZhQsEbC2ey2J8tA7asmR9
                          TZwTDMcjtoCeMpPn8zb53iTk9SMbIa71ue8c7St/e+o2CndGPlZAA2+ffLr1kdyD
                          GNPnACQl0Jok3xRlbnbseEOgxW34Fla7Z/nzW+UoEXi60ssg60bljiAJ6UQ9jkjw
                          pX6qG5HbLOZwjp4ujPnfsUoR+s1qGQA8OoZ3RzJh+HD2Xck7XolDsIfbqpYHuzIY
                          /AHfj0z+6WSYsNwbmIGVYyf4OxQ1lkpcFzIIjqEVyzRy7a+J7JA5/mJJqOhL8go/
                          xxrPkz57S1DsOj4yG65XMdDkB7/Muk8Cl+BQjrz2jy000XWNBS9Q/gTLMA7JKFEj
                          bkcwm8p0Iw3AnOcDSzLhD+pm/WawTLJfXVaijrz3AsMz2u8Ky9iaoNYKCiCZlloc
                          Tni8RrUb50EWuAVmdr15D6kopv0ath3HpqmVrNkM6OJxdFvc/DjxHzk6g6xLVkns
                          0nbgC0QM5m517QK1r/L2xhSbvqmVWxHs4otd9zPlgFgukMZAf+hJEyarm/QDsMqG
                          6HNoXC87qJ/yAbE+eDkYhF+czDSPC5Du8tLA32NdThCUb1ntPex1GLNR4O+PanR+
                          HRXZ3KFCsaY3DqFuV5sz1iZGmtxTDY6/S0nMg6ZAI1onCa2zIJN4lLA8dNVBtn8e
                          Ls1JphpEbK27VOS/SX+HkGJ2F3eR7b/BoBFkOjjXZxdr1XkqzqbhcIucHPrexjr0
                          iadLqn1JJbSQoBy2w/lHLqYSGA60mtDmsRm2lE6qxRlxYmGPTMLekUY13Orzk6e3
                          CdhHmpPh6/YaVtrFIOXs/Bd2SfQeqzxaui0LRvZgV9OAAC91p803O5cLRT2Xn4Sg
                          aovkRCQDAgMBAAECggQAD1ZDfIY0t7Zzwu+9Bb6DRh5A6aUPb+Oa1F8QTgM3m/Fk
                          T/1pO67uuIEXllhVQcPpENL29Pj9eb1oA6ENJNZXjliyCJfQsvKRY/M+1LS45pnd
                          VapVmkrcdOdV1YOcFlSZ0NeaWqou2wA/1nGtGEB+SSwCQwW4Ck0wezy//17EZRoj
                          VZZWTkWVQjAPOMsK0a8ggfKSlu9dw1YFkxHpZ73uzUldQkN845kJMvh3iifr6lT4
                          iu62k79svn4AUJXozz8ZKBPcpWW9tIHI26bYSokWTst5eEyVrJR2CPwY5CbX+25Z
                          1Snz8pkqQuMUCeszAzdjpDLCkKFwxN3q9JFg6mMjcMbcDxHtizY9HMpCVlXayjtc
                          2zXGz6FxFrteXvSKXA6KEn/HyfeeMJKbmUTAb0MF+7dVZ2fZlfesejeUKSTPwlLt
                          ZNDwaPIn4TM/aK6x73r1oYzVAGtLV1tMM7+TsWJWDpz/NHbvCIRcbe/2HaZsF2d/
                          yLLw2NrqXiHgi18w89vxg5RgsU2+G+PcMBbP3yuo49choEDAllvQc36KMUqAYNR/
                          ch6ZyfazYHEJGzC7JhUR4BOccW+meVDQyCBELAeBdSyV/mVuxM/F1N0tYflTaJc4
                          3mn383tmF8yj7s6j9R7a4N5Xa/cln8qTUCNCxLdi4J6FOEdHsNI4OuC6xOPpkBwJ
                          Vn0UFsy+RjtImTGFe2xrDDhZCd2KN6ueEvzhkF5VLhE8PobzIKU6YA0QG35kiw3a
                          vZApHpRPryiP/x7HNbHO0foaiEbdsv8SkwtFCrxU5QNfcV9OxdG5UnQ+3MyhYjZq
                          MIaIW7Lbv2lWr1mX3gOJw8M1PZA87dos2HVLcfM8cMKyy8fcxlFdvBusXmHDspjP
                          w9zoXruWlMKTtR5U1Ev2ESeueesVIO7QyV3L2UA4estqTFYd04j7D7b6PJYaoO8W
                          aQIN7amAdHJapsGi8HNPzylRqrYRn6HxHQUsnu1so+csHnSK64k5FCUQY1VjF1kx
                          Afd41gwfmsvVzbSCzT2GWsvHg7nm+YH26K7av9YLRO3aDEK019xsqoBMhRTm5udd
                          O8R89vVxvOPf5AYDqoGuJ4Bsvj+1u+2VKJw1VTdWw0vINER2o+aFZ04Fuvn4kUEE
                          CAYVub/Y0coKvb/E282yoztAAg9e7I6b9iXFoh5gB1db4BRKnsZUv54v0p1snlit
                          Ec4YtWRkIJ960v6bbfxUuzjbPyEnSCdKbvSHIpg7ZggKbRGX2itzPo/PCDMGaHJt
                          l1N6FUS4AmZAiV7IIGlKyb2egcwnZ1HjBtXqVGQNN6lMXDz5asE7sj9dkPJaBeUy
                          MMdh+cyBe9why7tDkIrViqG8YaCzS7VbmuWGsra6mQKCAgEA+SYHQawKElf4ZnIL
                          /bP3MTl2K4rfF17vhL4TaACYdZCCYnOggqduQsOhtfDtwp4Sj8fxJpXBK5jO7AJK
                          4zNLlgaGiQSvW8OIH5EMhLBLKWuOu7w4a/qMV0M0TiGWcC2OJshg9lhZ8Tt5Pfl9
                          MzzrGGDyqx9rZ/cHQ7SF5PcLP2Yx3/G/IHXdDpiO8T94rv0fw7WU1YUCW97Sm56u
                          CNyfjFyLKZh8OBLZZFrQltJkAD/U6E1xmp7VBVasr/3w4im4mw1rmk+9H8RL50Wv
                          Xgl1gd+aOW3N8vVSbfolVc6wTXBCq4AbB1Hd5sIP2CaW0nf3BhIwbcOr/aDpEb/j
                          WFVhZC+hzEbb4LxV5RhqvnDgQyp9g71wwEcHsC+EcjNWLFe9NuWaNpBldYX4tzCE
                          IBVkoz5SJYW4e1aiomCAY3nwDXcfuMUEle/QklHrO2X41qVBEC03VAUARZTfTbKs
                          yQ7OUI0vv/glJR8Q/9/lm/fgMFuNE67Vtl2V7OZdlSrdr22rHc0JXcZp+SFjyziP
                          cZwpw+XEgNBGQxb7WNLeqpRnYLAurV0fPIrMK0GVgbkLCFSj6VWou18iadeS0rxu
                          HiwHX/uILHOPDUXlF2eCyAr35ipVuN6JJO8TN87kf4yD4B1NcaEJxHjK5A/R90W/
                          /sAG9h6fH/gHjCOcEiVQYmR64jUCggIBAOUMaUk6ssJq/16S9fNx8sHjxMOidjao
                          ApfqnAldEXAiW0uDEqPaOhWkMmtarTXNp9l/X9wrWtCHeZPMgt8pNSG6mQiKrBvX
                          dT1ItmFSIY2E5+BfXzVW7bFXPKCB3G+J1h6iwPD/HtruZ9sYHNV/M9JHettb26yp
                          3pXxJHUd/WqFuu1Iub+dmmxq8XmTuYOdzJBgu2BDTmtoZxYrg6eikwpgZCh2sGzP
                          3jCCCmOkgI6mJBy7ZfmW7e9HzKKNbKAw4O7hCeVVEi4ERDxXwQjV9Ay3LsRpMpxX
                          O2ZeTlWxWH1gwJoo7/Ak2TkmriTRB+iPUqcgN+O4GmeqwvVFCxR0YiiPL+4mq9LQ
                          wT0OU7myV+ur0Ur7Wb/v7heItfKroxzWJfoFnWFYQKj0I/eSeuKbTn1SyixyQcbZ
                          uHyLVoaTqkPRyM0GINEqUgvJtQkjh/z6wMhRzTtzvLA7XpbiemG+AkvzZ+8dHWLP
                          uWVPj4y74r9JmLvcrrgdZ0s1jlsEL4yKYeRpesu33iEbuEWk6c1itqxj/eK2shMO
                          yTQZ5FM8CfB31wmi5UJLAcYSmMSCuII7WosJZH3dyV5uWTpLZAaSB7eJekvsvA4x
                          yBfK2M9+3uH3fJNU0o5HdCJPMwbHFrNqnYu0xhxQB7kK/rKedLDOPwL0/09s4nWl
                          QeHcEShoJLRXAoICAQD3v+H9YucNAJ9It+XGnXuUXlBs0gYvhj7lH+HKTLVOSqns
                          3o/g/D8/cqvOcUrseSV6Bld9h/LzuFsjAtCXBv4FrG2BuL/rnw8wXJs3IttKz+K6
                          OltcvGNrrq9HdkzTNemiFSWeMZMWt45Dm2DtX4ljz5vfoDm8wz9dCxkN6r8rhyLX
                          TtxAmhN8nSWfLf+C+r/obBsZC8+hrXx+NRdYRpL9D1VuwmvbkprMGSZMo9+/A7pi
                          Wgg6ufCYA21rADjVnKkuvfSfGOW2vgrAamINP5iy0bfZnZ/rFhmmtNUFc6eLCbOy
                          OIwoBjeDbLw2s4DMv3BLgDDaJXZUmfrJpKecwiI7bsYUjO2+l2lOi64xu6q1/32a
                          T/nbqYYyo72vle793y2PdleYJJRPfi4pc7we70cIsUMcftFJDIhisVVaFfooWamY
                          oYmC01ry9TTV9vuv7do6DMx05xgzGOvIpoD82ZU9MngmC8pcFH1iA7GeG6m6TH+H
                          8BYh5wPb8+NhHqQc+w/qbWX/8vqUOqiyf4bccW5yl3uEoBcORb8gv2ed9j6qPefc
                          iroyCM8nwGq7+VbILOplb8F+uQZOe4hLuAZESIH45vWtRigdCcDaOhspcwa5wKVH
                          VTrJGFdi6n/7ea31YQ4OjRVaYsdWa4jdu2VFHIyPlzmin5BZwVtEDAjYHpS3dQKC
                          AgBRlEATsvJkSJO37YPoN1eNM0CrpTuRb/msfgUhWKKTW8lEdeS3s0wo1RiYH+29
                          UghMcQ+FbXOk/fuRZq/eJ+EiqEFFR47RQ8YgE7vRod0NeJ7VzWItr05tcXLIgDgx
                          CdjXhIRP0a39sBgRct8iM3ITnR3m7yqorr/2i7K+e/X8cLEJPnPaCZosr1JeSP00
                          IYnwimNyf8Z4fvDodosns8HHWlmSB+QCfW7XvBlTMA4RwJ7wFNbXNKh+JwZ9hv1/
                          eKlEq6ZIpioZda+QBnlcWkfYF45yqj06bd9cMI6Z+tZXoZQ31AjRcW5k6p/vwPue
                          Gx4HJHSDiNjuv2U80mCF4oXriEQ8AE4Ggg+xXV74rsqdx859dFSdBim4/BpB2lv4
                          M1XHXSSWvUYaZwpAbU2TVFl6TXhwqClBV95bjY091W45RYjNbTdXCEm8pRTzslIH
                          CpCLSIdee3RjGGIyP2vzUCelQYZtJeOHhBC2QsYQDANQujfKAWnBbceSg/q19CGz
                          Xr5LCj6QPGbDSAoz0+7qFhSWBe8xRnzaSNPk2Kv38VRg724JopkhKXHySEFdDGoH
                          CHjROIEwS0QjfA4PszZnGK/i8PY8AI9iRtzLjJX4IWnk9a7LEtUDk/OLHMZBzbsK
                          IBkI31QIVYDKqV3Z5JIPPwY2WWhts4xc9oUmmqkJyT35dQKCAgEAxg37N53Nynhx
                          48siVsTN7Yg+2lidvX83JLIHul7Dav/mx9kP0+14J2VukxH6syiOKNBK6oEgvsr7
                          7fHp2jp5CE1cgszNLmjvTxu+1zCjEjI+GY36DY1Qt4d7zEqCLldpzJS3SXRXPkcH
                          nsvdfygN5NTq2FawS0TThHCJg/QX/Cw+Z5lXvprSjBLz+B3QYUojgTzKnj9fNQlj
                          zsHcfpxv21U8vxmgwU1mNYUE0QCVagf+UrSweGBNaY/en9Y/P6xAeZNcu9xoRNX2
                          RwcFJ3CxaXSLYsKnguYQbVT9dzrZAkpi3TWzP/WtWvJ06inb9xvvEoQSShWPn97V
                          iay3WFwVQaQPXKTgDPgXKQgoqY3rhziVmsWq935epaDIN6DFyPYSz+S3TVCtlvSS
                          eZhiamSFr8mPf1sft4kXHiFAP9B5wQ7pxhgYCLf4jsWBMbCHYoMOIKDl3lnva5Ze
                          +FCtYunPlIbEAthGdVJ7qilyRD0qQqT6a4EmQPg699X5EsCjRBV0S4VDOlyPvWY0
                          l/1Hlfxfl4PmTENT6cIGuGqK5lNdQN5qcka6hbGRfJWgbbk8b4KXvjTTrx/7F1Ql
                          +iIO3fDTwCkhN1CYqBi0dEXQUiczfrsSqA+VDuT7w+2Vatdk+G1rCkAONwYHrRKw
                          X14Oss4pRGBM+K0nwFVKXadjdxhaEn0=
                          -----END PRIVATE KEY-----
          timeout: 5m0s
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

