# .github/workflows/deploy.yml
name: authelia-deploy
on:
  push:
    tags:
      - authelia-*.*.*
    branches:
      - authelia-*.*.*

env:
  CHART_VERSION: 0.9.14

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

      - uses: azure/setup-helm@v4.2.0
        with:
          version: '3.16.4' # default is latest (stable)
        id: install

      # https://github.com/because-of-you/helm-deploy
      - name: 'authelia'
        # 镜像
        uses: because-of-you/helm-deploy@master
        with:
          release: 'authelia'
          namespace: 'default'
          chart: 'authelia/authelia'
          repo: "https://charts.authelia.com"
          repo-alias: "authelia"
          token: '${{ github.token }}'
          version: ${{ env.CHART_VERSION }}
          value-files: "charts/authelia/sample.yaml"
          values: |
            configMap:
              session:
                redis:
                  password:
                    value: '${{ secrets.DEFAULT_PASSWORD}}'
              storage:
                postgres:
                  enabled: true
                  address: 'tcp://${{ secrets.DEFAULT_DATABASE_HOST }}:${{ secrets.DEFAULT_DATABASE_PORT }}'
                  database: 'authelia'
                  schema: 'public'
                  username: '${{ secrets.DEFAULT_DATABASE_USERNAME }}'
                  password:
                    value: '${{ secrets.DEFAULT_DATABASE_PASSWORD }}'
              identity_providers:
                oidc:
                  jwks:
                    - key_id: 'public'
                      # https://www.authelia.com/configuration/identity-providers/openid-connect/provider/#key
                      key:
                        value: |
                          -----BEGIN PRIVATE KEY-----
                          MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDUHbJTeTyKM03P
                          K4Xfa9blOoAuNphz0Ejvmrlkn43tWw9TgavqoMS4GUjklz6xst2PC6lZxmpPXZjo
                          lh/8rd9vxzVFA7kxe0ngIneCXd0fr6zAZkq1vaV8g/6gY1OiMQmPOv1yyki2WRDR
                          Hsxb368dDe6t3G18XNVnbzi0aHpRG1OS9ERviB777JB187Xlfo5lS0H7t+MwIfEc
                          ksiO8Txsu9uN25tWbETy4eaGZv+Z5JF6LHXnxS/BD3fnbTG8Z5NsxedgHFE62BgF
                          qkp9eGn2ynrc+qu6RNqKFLtph0Y3VRGlTF8LAgPI7+iZA4w7c9DHwmAsVB7zawqs
                          FctX56NVAgMBAAECggEAWSbWIaFuIYPoqy9WyA3SN2w8HbBSqTKcxSAZ1cH97An+
                          yhFRSX8iz2HJMlKjRhqwZoP3PMVZP1xOfUtDzHbj11459HTZLIPuC+dQpZl/6+Zx
                          TDhyJCq+WDQ+G/lDWIMVyn53sfx1TTboC4zPRbohJqwJakegOMnn495qTeEvr9Bx
                          Qx7YuFrvx+pwL8b+tStiFv7fPWFEwdXJIOQEIOeOMs4Cxx12dFvsKySxvU2AndXu
                          cfsS7RNWdOS4yw4ZkL00W7PQwOL0HvJFzIVb8Mn4MXk1TTlOUAnZcVYRjF0bVUZz
                          fPdZpTD3JWAXbT0fVKYVCjcWjavsGq9ZBXuLLQ8aDQKBgQD2V6DmHYfnZWefadQB
                          hgjoJkSoyH5IXpoxUmDXOTUzXi7apECPKkYixQMWMRGRCGcMRvnKmf2zTvXppd+c
                          z+liPZLImqkWHWzPkiautoP6wIl5n/Wr1SMfAQ/ru//W0Meb3pykBSgCYwrGqRJn
                          /AeZA8FUoii/UhM8iNrTxwSdTwKBgQDcbo/TndU0K0/0ynE53AGMPQcnZOfHt1zp
                          /K/6FMhSKL+Q8EuGF11E60pO1Rgvm8FFJbnshIIq2kE00FYCAfIC932UG/z5uV3k
                          lMHAneLQOgYExnrNydysro+zOapYhllVNzyjg3sJlTB9PMA0Od7VOEdWPKUNGEzs
                          wNSsJlk0GwKBgQCVMQ7+LsZfKvfuAP7oCVAdoQeWHQ72L209D8IctsX0nUbNHgsH
                          abfeWOj8qK0V5DvcoKOpw0d2MA0Y+1+JLhYPbHEYUyqyfRGoSMBqsZkO5UqdQXZd
                          IhFKNq94unxAkmNBkDnX0FOh1m/xTvYZyfakAjU1V5xL+p4x3ESDXBX8WwKBgQC2
                          hopr5SaU40R642LsUSOq9yHEWgae1lOGoSkqgCj79yfhIUi4SQJ/PgGy0zsKuQNJ
                          eZrBoVuTllQmIlkFooy+Lib7DE3mjrqTuyXQlCwq1dEEBUHMw1kKWCU/eAF4+g5g
                          xLNehlHMNpAHM9XHqR++GLLhUqgs9rFD3cx8m+iDfwKBgH8Gude1UKUC0l4cviwp
                          GBF2F8zBAj7zoDUivUfQT3KTrrzo/CNzKtC0+1Y1cU8uXEgb3cEq5a4x0MgO6PCZ
                          WaFFbcbt93qAbX/Pv/SSQkspfahXK+OfOiD7s3gjvKElkRyNsmuVD6XbdiRDRjjO
                          pBy6IQX4sAUBbtnXdUXPy0q+
                          -----END PRIVATE KEY-----
          timeout: 5m0s
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

