# .github/workflows/deploy.yml
name: authelia-deploy
on:
  push:
    tags:
      - authelia-*.*.*
    branches:
      - authelia-*.*.*
      - traefik-*.*.*

env:
  CHART_VERSION: 0.9.14

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

      - uses: azure/setup-helm@v4.2.0
        with:
          version: '3.16.4' # default is latest (stable)
        id: install

      # https://github.com/because-of-you/helm-deploy
      - name: 'authelia'
        # 镜像
        uses: because-of-you/helm-deploy@master
        with:
          release: 'authelia'
          namespace: 'default'
          chart: 'authelia/authelia'
          repo: "https://charts.authelia.com"
          repo-alias: "authelia"
          token: '${{ github.token }}'
          version: ${{ env.CHART_VERSION }}
          value-files: "charts/authelia/sample.yaml"
          values: |
            configMap:
              session:
                redis:
                  password:
                    value: '${{ secrets.DEFAULT_PASSWORD}}'
              storage:
                postgres:
                  enabled: true
                  address: 'tcp://${{ secrets.DEFAULT_DATABASE_HOST }}:${{ secrets.DEFAULT_DATABASE_PORT }}'
                  database: 'authelia'
                  schema: 'public'
                  username: '${{ secrets.DEFAULT_DATABASE_USERNAME }}'
                  password:
                    value: '${{ secrets.DEFAULT_DATABASE_PASSWORD }}'
              identity_providers:
                oidc:
                  jwks:
                    - key_id: 'kafka.acitrus.cn'
                      # https://www.authelia.com/configuration/identity-providers/openid-connect/provider/#key
                      key:
                        value: |
                          -----BEGIN PRIVATE KEY-----
                          MIISRAIBADANBgkqhkiG9w0BAQEFAASCEi4wghIqAgEAAoIEAQDQqXpsS8dP0rwj
                          gUFLWopSZk9n4MCBo8lrklz9H0cJxc/vo2cuU2FBMlR1RcGhylMVq7myDS8WDVDA
                          sUaUZFKImJ5yi29fm9kOWLPylCuaOP5zzQGs3D4WsOdNqsPbxbNmBhD1U/q0n/+k
                          9ItRMa4ETwqPE4D/3pMsxruVysmHwOaO9ilapUDcFORB5UBn7AdAxDjgIKnb9/AR
                          VunKz/MJQI76Z/GSXEaL1qmpJuJpXsJXO1DUVGgsqyabCKGxyfPpfD966f233ewE
                          4TQ6imX5OhZCjbskI6GY+Ojfhvp7rha/s0fIGczwIt8ItNjfAPGcdaYkSU0p6h91
                          PnJQueZnnMxlXiFhV1hfl47xqUoDDnw5LaMVm4Ae8pq7BBLcwDlATw5HNIcDzYTx
                          3MZeEE1P2YpqlX4AHq4oi1jt5kTXTILXeYuLFxT/CjNo2AwgH4wznRpK/qfPG5Lr
                          SVQKj2WL/lFDGfjrngjghr8cl3wivOliEYRHp2SLkiYV9ca9YAi3e33WBTMdz4Bk
                          WEO/VqvY/b2A+RK8RbSlFq3mFSJcpqqRD1SBqbPex97HoPuiE2sTmHUO4uqNWfUO
                          mPzsrGCO1DD/ojFGobu0ui4VkcWi6MZM3RZahO8rh6sO1C2/NU2zZ2Fo1Ga58iK7
                          jJY50EuaNVtrW5gJA4Xq+vGHnfxLRFn5mg1EpTHl+ByBuUkicN1UgKgIig1lX2zo
                          lEc8TmBYz5iXtlGZw+05S7F/g2O+OX0ceAgCMgJ3HJ4CAMph+oNRqw8CaC6Xyqwj
                          m1RE7MVnyZgbOjMglFV3M57KP7/iYa2ho7yUo4kcSo0BfV8yUk/ow9GdCzf6s1ig
                          W8tDxe5uKMfGpN2LRrwkRom+P95eNFd+CHsWSRxe3RhJrWoONWz4cGcZvIkRl7ka
                          VPAOMiPspY9skrjRPoukmauhQ7aq30qC803XFJwkQHmMpvT1qhLwoKdQ+GJ0SN8Q
                          1WaV9yTWWeQ/RRQChGYegCbF8Qup+3WyZfo4i8BzPTLB8uAG2UU5HEsQ/DdroA1S
                          wuil85Fcg3zOdmqjPAvruzVE4vVHE/AOci7e1hUCjGe0mwCfuXYSk25WEUyQmyn/
                          C8RHt3iYjEWnZNskq2z9ptYFI8RBM/K3bdfw7jp9YQmaJ0YQyjXX9OYcmaMUGy08
                          hYz4Xe5nU7jx79Gb9W1Z4GdgjPcnJJvVYCUUsGoq4lKctKER16EUyJVQC9IWK59U
                          ur5V+Dz2rOb+W6kopciQ54cBL4FgT5MbX53CBA47WgHZJAIGwm+HlrHCKBE38wed
                          UZ5KMaPWr0HD+F99jAJEpvJ/b1gROyg2nZ47kxPmB0KaDtDTZAudRStP+yZNznu8
                          tDvMzio3AgMBAAECggQATLPwH70fcDVcGYUbFnMa471eNSZGPaGSmit8aUPFHk+L
                          52BevoXB+3Bf4ZgZ3Lp+Hjo5Eb2M8INGiv7fng7e0/2eSSb+ctvcR0zOIT7cZF3N
                          E45prjxrynWPIVrDkpczIi7arwQG5bznAaEvUVJ80HKpw/x8cBJGcbBAJokb2f5M
                          AoN0ojCbDgvT+HEoYss9w04eRi1bo1OZ+RXE7VvR0DXeGSh6gb3P5Pms9lQn6Gn/
                          8IcKaHL6tGjZ0SW0IqHFOrAEuc8oCB3Y89ZBF7/mSl5S7nYhM+CxN4VQPVLl4u8U
                          x7VEjscFMcTvzciE7Dzxk/0fbLlRVzYMCFJDPW+Ixc+6xwx6Iskz4DfbQPRlE4iQ
                          m4guKfQ2fanavSJ7OJCkuwIUkpI5i2lSFIJ+nPdLJC4olpOLdMnSZW8L6q+54Jbs
                          hf7VD/UVL8d1LHY2xtwx8osuriC8WQKe2ETlUthxkKuU/aCfgyVdyANgX0dER5TA
                          Cd+8i4Z6DGBWBb6KJvUVXzVTBYh1yOCNJtXXWY+nriVgMvfcLj9Fb2ZN2IUuU3ak
                          vpwvCVbzmtJID4Qa2/Jdax+g8C7z37AQyCPu3aVj/Tz9IgtiJ7+uO3oxFJa4WvFM
                          a9bdr7qsHIlLlTDj/CTBAlDfWuSxOmtK3zyHwIrUL8SrbWSHF9EmukEy5hJqOtQk
                          JxKfqVyANNukE8JX+CP6r5Um09ixeXqdiWHMKd+3zHjwbgUOlTx9/bLwdFaGcwaH
                          K/e+n1kGA+F+nC4Jobvvk0vxCe5N6OZSuQ+nZc9LxwAOeGitF9lyJLh8U1FSovZN
                          3OODdXIZ1ywu+7LbhprHVNABux1WbrweiLkQKpEowk0K7pDnswWdAsPZDe1MlbTV
                          hfOXp0moyztxhobrYZVtSxQhSgENKmxN5bpve8QYRVSeEWxbmthUQYXHR7mW5odZ
                          fYLq3wrC8P28769iWRb8W0NtB5FwKG+4deQFV0vGU+FCgppiNN5jNFRcbVPGHTj8
                          0HIXJoQ02WFCu3+fukN9aSifn9+fwaQMa3lYwCH0b8CWOdj0IrmK+6nMiv/fJlUm
                          Hn0pRJvRXDVMbMpRvk/5+cm9uvAZArcb76ZMrj2tMuPvTFrD+85IduplRc8YME0E
                          8MiwUfeSU7wBxT0LiI1h6PmqC9AnI9XKRPdGIOIHZgyqmSOaTjgDz7Y8e2QLKjzn
                          UGGsgwcog46W4MMLF9ecsSI0lwHCcUh/tTyl28M0uz5WKdjt7jXztanAoN+LWF3Y
                          6yDxVvUQ+iUaxgswOalvWKkNxxvxZIRozHlx/XI8wX5hf1G/c5B8eatRuSOKtqfG
                          xIdQTLoaVzAfEFoK0ovPRiHm+NbR8tNbWo0U8RQqqQKCAgEA9lDnw7eqTXbZk0QW
                          IAn5ruUnesryqlbNCpS+Utzt2SOWEkcN4Lr+JDolQcywxQVZAJumHk5WWWHpUpPW
                          DtBmIRvAfs++8Cp0BOO14YLZWaQLl3J+QCl9PkVkb/+xHmFtL4bEojKYJRlzX+A3
                          f8NLAlUl1N3QlmV0jt8YwZ23bFNzTmMX39RUFyNXKZxno5hP9rq4qIejzx0RLfsF
                          INgoGXix4Q95pYCKdPjvj+xgYCdh9rZLQLeuzQwNaIxTJhupAVTG45/8izhfA4ah
                          puytFzTQ3rKrNkk+rHSYDQ90kB4GDqWLtAoCx0QQw3TkC9RYuAwS+qS5m6ujWfhi
                          FYrl4WZ2wKrpWAP5tUnXnYAF9deKripd4vcxdkBo+FNa0WrfqZ1ZfXS/+l7eeLTX
                          iBjDfkyhyL/tB/fhIbq655MoqQBCiJrLWWebti+PxKueQd+eF0kXo/TDgZWlmy8M
                          FmI34b6b+iiK46eHgIqOFkz0GvQ/mNHsCwYcj1uN5uz7xQ1sxjSzPmixdxN4fiO+
                          xwgxDa5v/yztZuqpYEBHEZtNUwlzq7ay1BwRAkSCubDcgs8A4skJJ7Gacz8+aRGR
                          hJkcKlwua2TSzrkW9WcK31wukm1O33vxTIyhr427IUnOX7h+tP5RRHZu8yjZ0Bjn
                          TrJX7QrT2ztBS/LNPkHShh8dnD0CggIBANjdmM7ejpfIPoseDSEvNN/pI5KrWzTU
                          knVT1Quoj+ol5312t2rtTE1QdAoDBSwD5jutUvl+DMLXmAcIJZduSIzv0bcaN4A2
                          e5APCvcSoz4hvrAzrt+RBKSu19p5GV6LPfRf3VMjjjLD/DqS1rU4iIKCzXiFjxgs
                          LSquBZNvJZBhnDPCJgIPxTdo6md/qUFs0T+BMXpOcs3sHRJLbBaqsG6EOVxPEvZR
                          LqwLoTBq5A1lbQu4ib7b1WY6gQ2lo/PXI6sSby/dwFh19pZH27vtlEmcl/tAy4Xm
                          CI/03n8IfZyefQ+BS5MXbvL+87MU3GEF/BDUD6cVzIS4EGS6iT5rTAG5UCDMlW6n
                          /psdFG+9hDr17hXdbw+LVjc1jSt0YW02PQFXofeVMlazCcVHa4AAXsBhY7ngKrVF
                          ILKJLBocAHdInuVv3tyOWwqlIH3KKD3briLHULgACTmOM46f01q5F7SzGCHotN7Q
                          h37jMWBUzod1oNVDqgKP/81H87DxjEJYXtfmDhy99T3voI0aHuyXslKn7uDT5T50
                          JrtuutE59dXI7wtlQMKGoFZCDKR7B56ESbvctIrJXvKmb+WNtkbXm9MKkUxzpsI6
                          9Y96Gha/S8g7C0cBsx4QRkBfK7WeWVFqMKfWptCYAbKdYOXDhonDYTej6ReawjfZ
                          oB+x/EU3xIODAoICAQDQDDgmVOywr3FI9RpnB2Xwtrdo/SCIhfZ8OHSlUtxHKsqo
                          N4HeTrM4cDBl6nlogILTg6SFNo+ywYOs7xe/vYB1+JXXxqs0+fay5o8KolXpZCky
                          S0+d7C1QOpaCDwtQaOQrX36YrXla5KtR0PWvoYmqt7bTnGOBlMIlpwSnDQsPoVDk
                          ZciVkydPv9bwW54iTRVFhiNQnfjbiGapWrvTKSB9mzdLrKGIDBFmiZj3DKW+saUK
                          GKFpUXyAzuxIYTYeGwDeEfhH7SsHgJ6oQMArWP8+earuXyVEHguk6HpBlctTqzhc
                          iLF+aXI9Ux2BqiqwXzRsiC5DrHzlosy/wo8+OOrAPqaRSAr9/6Wb3XoUGz1tkBgf
                          0cMpYLdTdUX0cZtlBQtTnYcn80PwOs9YTw85cgk1lY6VHJ8dut5aeflCfka6sHCC
                          J5UYt+2KrZOWf4qVg0Zpzp/8KVI1EuwlLlDcWytuLmxamIHvleJazS0EYw1P8vwA
                          nVbtXMUkxSUPZx2lLBizNXIshYtX04dTq+eI/z9Hmg4ZD56Z7h0QIlqk4XMnbvVX
                          lWJozCgFrU5pf5xRlHzgEQP9lgKp00JoxqENybFDikbfCPMSDr34m4dQb/EaVt9m
                          3q5KhQJQYLste8SnjxLe12xXEl3WXqvTHCXLj9G6cwnMw7j8aGG5cylZhdCh1QKC
                          AgEAxl1bqs20DG3jl4izZckySiWMnloTIS3XkW5PD0zt5rUpG3/9odbQ1l9i5M2C
                          a5Jdg/S0UvXTYl2l97ih+fOsdQ3f++YFIkezmj/IPdtUaj6fl7iOmnyhjKlJU9M1
                          O1+OGfueDLAXH6RZEJLDxhuh8g8HNtij3O57mfB3tTYTXA+Mu2M5NOWL9XUIBAen
                          n+qTM81OnpsnM+hnZxaKFemnXE+h0CecJqZ3VHOGyyza0M4XgoMXq/aVKd8VsI/0
                          edQuEgrYnSXvDHtKRIgSG8Hiw7py4iWQhDe3WUYYRoZTr3Dg38/aev8SQz6lVwcb
                          1buNpy7x6llsK3HZvOlLJEcszN7exkGb5g3QO73LtbHaQ7w0PNfBAKzo/bMEH91i
                          SG02PAYWZsqXsuotY8BCOmEcSkhK2fiL2CcVE3mZV4CJhJJulVtQtNmZuRD1uVmy
                          mXJZxAIgeU2/ImBKFIlo4DEx192Bk3KyDqUbaxsRTRYFm64ioTA1UAa7auAHrbAk
                          JYODrWQHQI8YxcBsUOS1qJ/RQv3M6OWpaQkBbKyKQVsM3LHgxcGmDMjr3DqqKcFH
                          ZN2IPEhS9Cfhq35GF+kZ847AP7gI069tt3gKqWR8fJYaEVrApACQAE3OlI75AjWH
                          aYsCWmNjTqXb169QtJm2dEi8ohJR4X9za3aqmpNJN18dZ1UCggIBAOu8jDQTe2+c
                          LG1LcDGkrwk6DNgMvyhO3cBY1GDvIkc7rrY8DX59CFz2fPgOOCNN+ckAZJD/kPdR
                          Pe4FoOfZ4159g4pxfTPBLqk6Ujiradnxk7xZiZ2QFxSbOEi+4wh+G8J7fseifaIc
                          adZKPThp4I5YhuCiE6w4UmGLYv1+JRqN3sqIYbo6hGagi/+oV7fFIttvt+DDCZVL
                          KDm/aLBbohiNox9oa3ipGXi6JozWFCmg9fdZ72KYcwp7SgPkqB87IL0QPWUTuo96
                          TuIwPixVX4HxGwh/IPCw+PJ9ypQq8vqJH+mHW4Dn2L6w+XP283yQ8FVKvRy8WAAc
                          ZhjjWqrVzxqZIELC+a8bAdJ0bMwe3vYulhe0MscAgU+TBe8kX09nZBCeEH7iTZPW
                          ///MIrnoiGVCl+JPDJ37KfdvZWX9kMyAT2CHGrH65wRVsUqzTpuWWq/RzzuwJch8
                          sj1eeNelnmFqmqUWb5DaY6NEaXyyEORsJtL9Xg3U6bosEwVSkdfNFPJgCQz+s+Fh
                          TGMfpJ8rpccb1Aq2npzwrDCU7amm/mvWEJT3APb8o6j3M580DH+EZCmm1ijeTpWa
                          UaZxWKqhQ5hu1McDktSoEYPKm/8iFFkTLj5jUsDLWHzMLTixQPwpzY+K91asIc8u
                          mgHGDOm8ZwiE6xScpIZYab5Awu6R+eAH
                          -----END PRIVATE KEY-----
          timeout: 5m0s
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

