# .github/workflows/deploy.yml
name: Deploy
on:
  push:
    tags:
      - casdoor-*.*.*


jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1

      - name: 'casdoor'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'casdoor'
          namespace: 'casdoor'
          chart: 'oci://registry-1.docker.io/casbin/casdoor-helm-charts'
          #          repo: 'oci://registry-1.docker.io/casbin/'
          #          repo-alias: casdoor
          token: '${{ github.token }}'
          values: |
            database:
              host: '${{ secrets.CASDOOR_DATABASE_HOST }}'
              port: '${{ secrets.CASDOOR_DATABASE_PORT }}'
              user: '${{ secrets.CASDOOR_DATABASE_USER }}'
              password: '${{ secrets.CASDOOR_DATABASE_PASSWORD }}'
              driver: mysql
              databaseName: casdoor
          value-files: "charts/casdoor/sample.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'