# .github/workflows/deploy.yml
name: Deploy
on:
  push:
    tags:
      - casdoor-*.*.*


jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: trunk

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}
        run: |
          kubectl apply -k charts/casdoor/workloads

      # https://github.com/marketplace/actions/helm-deploy
      - name: 'casdoor'
        uses: vimeda/helm@v1.7.0
        with:
          release: 'casdoor'
          namespace: 'casdoor'
          chart: 'oci://registry-1.docker.io/casbin/casdoor-helm-charts'
          #          repo: 'oci://registry-1.docker.io/casbin/'
          #          repo-alias: casdoor
          token: '${{ github.token }}'
          values: |
            database:
              host: '${{ secrets.CASDOOR_DATABASE_HOST }}'
              port: '${{ secrets.CASDOOR_DATABASE_PORT }}'
              user: '${{ secrets.CASDOOR_DATABASE_USER }}'
              password: '${{ secrets.CASDOOR_DATABASE_PASSWORD }}'
              driver: mysql
              databaseName: casdoor
          value-files: "charts/casdoor/sample.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'