# .github/workflows/deploy.yml
name: casdoor-deploy
on:
  push:
    tags:
      - casdoor-*.*.*
    branches:
      - casdoor-*.*.*
env:
  CHART_VERSION: v1.770.0

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

      - name: Generate kubeconfig
        run: |
          kubectl apply -k charts/casdoor/workloads

      # https://github.com/marketplace/actions/helm-deploy
      - name: 'casdoor'
        uses: vimeda/helm@v1.7.0
        with:
          release: 'casdoor'
          namespace: 'casdoor'
          chart: 'oci://registry-1.docker.io/casbin/casdoor-helm-charts'
          #          repo: 'oci://registry-1.docker.io/casbin/'
          #          repo-alias: casdoor
          token: '${{ github.token }}'
          chart-version: ${{ env.CHART_VERSION }}
          timeout: 5m0s
          values: |
            database:
              host: '${{ secrets.DEFAULT_DATABASE_HOST }}'
              port: '${{ secrets.DEFAULT_DATABASE_PORT }}'
              user: '${{ secrets.DEFAULT_DATABASE_USERNAME }}'
              password: '${{ secrets.DEFAULT_DATABASE_PASSWORD }}'
              driver: postgres
              databaseName: casdoor
          value-files: "charts/casdoor/sample.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'