# .github/workflows/deploy.yml
name: cert-manager-deploy
on:
  push:
    tags:
      - cert-manager-*.*.*
    branches:
      - cert-manager-*.*.*

env:
  ALIYUN_DNS_KEY: ${{ secrets.ALIYUN_DNS_KEY }}
  ALIYUN_DNS_SECRET: ${{ secrets.ALIYUN_DNS_SECRET }}

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: modify files
        run: |
          
          envsubst < charts/cert-manager/workloads/crds/acitrus-acme-issuer.yaml > charts/cert-manager/workloads/crds/acitrus-acme-issuer.yaml.copy
          mv charts/cert-manager/workloads/crds/acitrus-acme-issuer.yaml.copy charts/cert-manager/workloads/crds/acitrus-acme-issuer.yaml

      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

      # https://github.com/marketplace/actions/helm-deploy
      - name: 'cert-manager'
        uses: vimeda/helm@v1.7.0
        with:
          release: 'cert-manager'
          namespace: 'cert-manager'
          # https://github.com/bitnami/charts/blob/main/bitnami/cert-manager/CHANGELOG.md
          chart: 'oci://registry-1.docker.io/bitnamicharts/cert-manager'
          #          repo: 'oci://registry-1.docker.io/casbin/'
          #          repo-alias: casdoor
          token: '${{ github.token }}'
          chart-version: 1.3.24
          value-files: "charts/cert-manager/sample.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      #      helm upgrade --install alidns-webhook alidns-webhook \
      #      --repo https://wjiec.github.io/alidns-webhook \
      #      --namespace cert-manager --create-namespace \
      #      --set groupName=acme.acitrus.cn,certManager.serviceAccountName=cert-manager-controller --kubeconfig cloud-cluster.yaml

      # https://github.com/marketplace/actions/helm-deploy
      - name: 'alidns-webhook'
        uses: vimeda/helm@v1.7.0
        with:
          release: 'alidns-webhook'
          namespace: 'cert-manager'
          # https://github.com/wjiec/alidns-webhook
          chart: 'alidns-webhook/alidns-webhook'
          repo: "https://wjiec.github.io/alidns-webhook"
          repo-alias: "alidns-webhook"
          token: '${{ github.token }}'
          chart-version: 1.0.1
          values: |
            groupName: "acme.acitrus.cn"
            certManager:
              serviceAccountName: "cert-manager-controller"

        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      - name: Generate kubeconfig
        run: |
          kubectl apply -k charts/cert-manager/workloads