# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# uni项目一体式构建方案
name: component

on:
  push:
    branches: [ "dev", "main" ]
    tags:
      - "v*.*.*"
    #  pull_request:
    #    branches: [ "dev" ]
    # 每天 的 一点 凌晨 调度运行
    #    schedule:
    #      - cron: '0 1 * * *'

env:
  REGISTRY: docker.io
  Zookeeper-Dockerfile: Zookeeper/kubernetes/Dockerfile


jobs:

  zookeeper:
    runs-on: ubuntu-latest

    steps:

      - name: git check out dev branches
        uses: actions/checkout@v3

      - name: docker meta manager service
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/zookeeper

      - name: docker login service
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: docker build x service
        uses: docker/setup-buildx-action@v2

      - name: docker build and push service
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ env.Zookeeper-Dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # -------------------------------------------docker 镜像管理模块----------------------------------------------------

