# .github/workflows/deploy.yml
name: conduktor-gateway-deploy
on:
  push:
    tags:
      - conduktor-gateway-*.*.*
    branches:
      - conduktor-gateway-*.*.*

env:
  CHART_VERSION: 3.4.1

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

      # https://github.com/marketplace/actions/helm-deploy
      - name: 'gateway'
        uses: vimeda/helm@v1.7.0
        with:
          release: 'gateway'
          namespace: 'conduktor'
          chart: 'conduktor/conduktor-gateway'
          repo: "https://helm.conduktor.io"
          repo-alias: "conduktor"
          token: '${{ github.token }}'
          chart-version: ${{ env.CHART_VERSION }}
          timeout: 30m0s

          values: |
            gateway:
              extraSecretEnvVars:
                - name: GATEWAY_ADVERTISED_HOST
                  value: kafka.acitrus.cn
                - name: KAFKA_BOOTSTRAP_SERVERS
                  value: kafka.default:9092
                - name: KAFKA_SASL_MECHANISM
                  value: PLAIN
                - name: KAFKA_SECURITY_PROTOCOL
                  value: SASL_PLAINTEXT
                - name: KAFKA_SASL_JAAS_CONFIG
                  value: "org.apache.kafka.common.security.plain.PlainLoginModule required username='${{ secrets.KAFKA_SASL_EXTRA_USERNAME }}' password='${{ secrets.KAFKA_SASL_EXTRA_PASSWORD }}';"

          value-files: "charts/conduktor/gateway/sample.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'