# .github/workflows/deploy.yml
name: iam-deploy
on:
  push:
    tags:
      - iam-*.*.*
    branches:
      - iam-*.*.*

env:
  CHART_VERSION: 0.6.1

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4


      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}



      - uses: azure/setup-helm@v4.2.0
        with:
          version: '3.16.4' # default is latest (stable)
        id: install

      # https://github.com/because-of-you/helm-deploy
      - name: 'lldap'
        # 镜像
        uses: because-of-you/helm-deploy@master
        with:
          release: 'iam'
          namespace: 'default'
          chart: 'djjudas21/lldap'
          repo: "https://djjudas21.github.io/charts/"
          repo-alias: "djjudas21"
          token: '${{ github.token }}'
          version: ${{ env.CHART_VERSION }}
          value-files: "charts/lldap/sample.yaml"
          values: |
            # --- Enable and configure external postgresql database
            externalPostgresql:
              enabled: true
              auth:
                host: '${{ secrets.DEFAULT_DATABASE_HOST }}'
                port: '${{ secrets.DEFAULT_DATABASE_PORT }}'
                username: '${{ secrets.DEFAULT_DATABASE_USERNAME }}'
                password: '${{ secrets.DEFAULT_DATABASE_PASSWORD }}'
                database: lldap
          timeout: 10m0s
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      - name: Generate kubeconfig
        run: |
          kubectl apply -k charts/lldap/workloads

