# .github/workflows/deploy.yml
name: redis-deploy
on:
  push:
    tags:
      - rabbitmq-*.*.*
    branches:
      - rabbitmq-*.*.*

env:
  CHART_VERSION: 15.0.7

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/helm-deploy
      - name: 'rabbitmq'
        uses: vimeda/helm@v1.7.0
        with:
          release: 'rabbitmq'
          namespace: 'default'
          chart: 'bitnami/rabbitmq'
          repo: "https://charts.bitnami.com/bitnami"
          repo-alias: "bitnami"
          token: '${{ github.token }}'
          chart-version: ${{ env.CHART_VERSION}}
          timeout: 30m0s
          value-files: "charts/rabbitmq/sample.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

      - name: Generate kubeconfig
        run: |
          kubectl apply -k charts/rabbitmq/workloads/