# .github/workflows/deploy.yml
name: rabbitmq-deploy
on:
  push:
    tags:
      - rabbitmq-*.*.*
    branches:
      - rabbitmq-*.*.*

env:
  CHART_VERSION: 15.0.7

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/helm-deploy
      - name: 'rabbitmq'
        uses: vimeda/helm@v1.7.0
        with:
          release: 'rabbitmq'
          namespace: 'default'
          chart: 'bitnami/rabbitmq'
          repo: "https://charts.bitnami.com/bitnami"
          repo-alias: "bitnami"
          token: '${{ github.token }}'
          chart-version: ${{ env.CHART_VERSION}}
          timeout: 30m0s
          value-files: "charts/rabbitmq/sample.yaml"
          values: |
            auth:
              username: admin
            
            extraConfiguration: |
              log.default.level = debug
            
              auth_backends.1.authn = rabbit_auth_backend_oauth2
              auth_backends.1.authz = internal
              auth_backends.2 = internal
            
              management.oauth_disable_basic_auth = false
              management.oauth_enabled = true
              #management.oauth_scopes = openid profile rabbitmq.*
            
              # management.oauth_client_id = ${{ secrets.DEFAULT_OAUTH2_ID }}
              management.oauth_client_id = ${{ secrets.RABBITMQ_OAUTH2_ID }}
              management.oauth_provider_url = https://${{ secrets.DEFAULT_AUTH_HOST }}
              # management.oauth_scopes = .*
            
            
              # auth_oauth2.resource_server_id = ${{ secrets.DEFAULT_OAUTH2_ID }}
              auth_oauth2.resource_server_id = ${{ secrets.RABBITMQ_OAUTH2_ID }}
              auth_oauth2.issuer = https://${{ secrets.DEFAULT_AUTH_HOST }}
              # auth_oauth2.jwks_url = https://${{ secrets.DEFAULT_AUTH_HOST }}/.well-known/jwks
              auth_oauth2.https.verify = verify_none
              auth_oauth2.preferred_username_claims.1 = name

#              auth_oauth2.https.hostname_verification = wildcard
#              ssl_options.verify = verify_none
#              ssl_options.fail_if_no_peer_cert = false
#              auth_oauth2.https.hostname_verification = wildcard
#        auth_oauth2.preferred_username_claims.1 = name
        # auth_oauth2.preferred_username_claims.1 = email

        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

      - name: Generate kubeconfig
        run: |
          kubectl apply -k charts/rabbitmq/workloads/