# .github/workflows/deploy.yml
name: traefik-deploy
on:
  push:
    tags:
      - traefik-*.*.*
    branches:
      - traefik-*.*.*

env:
  CHART_VERSION: 33.2.1

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4


      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

      - name: Generate kubeconfig
        run: |
          kubectl apply -k charts/traefik/workloads

      - uses: azure/setup-helm@v4.2.0
        with:
           version: '3.16.4' # default is latest (stable)
        id: install

      # https://github.com/marketplace/actions/helm-deploy
      - name: 'traefik'
        uses: chrkaatz/helm@v1.9
        with:
          release: 'traefik'
          namespace: 'traefik'
          # https://github.com/bitnami/charts/blob/main/bitnami/cert-manager/CHANGELOG.md
          chart: 'oci://ghcr.io/traefik/helm/traefik'
          #          repo: 'oci://registry-1.docker.io/casbin/'
          #          repo-alias: casdoor
          token: '${{ github.token }}'
          version: ${{ env.CHART_VERSION }}
          value-files: "charts/traefik/sample.yaml"
          timeout: 30m0s
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

