# .github/workflows/deploy.yml
name: zookeeper-deploy
on:
  push:
    tags:
      - zookeeper-*.*.*
    branches:
      - zookeeper-*.*.*

env:
  REGISTRY: registry.cn-shenzhen.aliyuncs.com
  CHART_VERSION: 13.7.3
  TAG: 3.9.3-debian-12-r4

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: modify files
        run: |
          # export TAG=${{ env.TAG }}

          cat images/zookeeper/Dockerfile
          envsubst < images/zookeeper/Dockerfile > images/zookeeper/Dockerfile_replaced
          mv images/zookeeper/Dockerfile_replaced images/zookeeper/Dockerfile
      
            # docker 镜像管理模块 ------> 加载docker镜像元数据管理服务
      - name: image-meta-load
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gravitation/zookeeper

      # docker 镜像管理模块 ------> 加载docker登陆服务
      - name: registry-login
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.ALIYUN_IMAGES_HUB_NAME }}
          password: ${{ secrets.ALIYUN_IMAGES_HUB_PASSWORD }}
          registry: ${{ env.REGISTRY }}

      # docker 镜像管理模块 ------> 加载docker 多平台镜像构建服务
      - name: image-buildx
        uses: docker/setup-buildx-action@v2

      # docker 镜像管理模块 ------> 构建和推送最新的镜像 ,linux/arm64
      - name: zookeeper-image-push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: images/zookeeper/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/gravitation/zookeeper:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      # https://github.com/marketplace/actions/helm-deploy
      - name: 'zookeeper'
        uses: because-of-you/helm-deploy@master
        with:
          release: 'zookeeper'
          namespace: 'default'
          chart: 'oci://registry-1.docker.io/bitnamicharts/zookeeper'
          token: '${{ github.token }}'
          chart-version: ${{ env.CHART_VERSION}}
          timeout: 30m0s
          value-files: "charts/zookeeper/sample.yaml"
          values: |
            image:
              registry: ${{ env.REGISTRY }}
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_BASED }}

#      - name: Generate kubeconfig
#        run: |
#          kubectl apply -k charts/zookeeper/kustomization