apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    showStats: true
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: |
    #page_container {
        background: radial-gradient(circle at top left, rgba(0, 255, 255, .3) 0%, transparent 60%),
        radial-gradient(circle at bottom right, rgba(255, 0, 255, .2) 0%, transparent 60%),
        radial-gradient(circle, #888, #111);
    }

    .service[data-name="Calendar"] {
        .text-red-500 {
            color: rgb(226, 232, 240);
        }
        
        .text-red-500\/40 {
            color: rgb(226, 232, 240, .2);
        }
        
        .text-gray-500 {
            color: rgb(226, 232, 240, .2);
        }
        
        .service-title {
            display: none;
        }
        
        .service-container > .flex-col > .w-full > .flex-col {
            margin-top: 5px;
            margin-bottom: 5px;
        }
        
        .bg-cyan-500 {
            background-color: #f26419;
        }
        
        .bg-teal-500 {
            background-color: rgb(0, 190, 190);
        }
    }

    .docker-status.dark\:bg-theme-900\/50:is(.dark *) {
        background-color: rgb(var(--color-900) / .2);
    }
    
    .docker-status .text-emerald-500\/80 {
        color: rgba(226, 232, 240, .8);
    }
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Public:
        - calendar:
            # href: http://localhost/
            # description: Homepage is awesome
            widgets:
              - type: calendar
                firstDayInWeek: sunday # optional - defaults to monday
                view: monthly # optional - possible values monthly, agenda
                maxEvents: 10 # optional - defaults to 10
                showTime: true # optional - show time for event happening today - defaults to false
                timezone: Asia/Shanghai # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
                integrations: # optional
                  - type: ical # Show calendar events from another service
                    url: https://gh.api.99988866.xyz/https://raw.githubusercontent.com/oooldtoy/chinese_calender/main/twenty_four_solar.ics # URL with calendar events
                    name: 二十四节气 # required - name for these calendar events
                    color: yellow
                    params: # optional - additional params for the service
                      showName: true # optional - show name before event title in event line - defaults to false
                  # https://gh.api.99988866.xyz/https://raw.githubusercontent.com/oooldtoy/chinese_calender/main/festival.ics
                  - type: ical # Show calendar events from another service
                    url: https://gh.api.99988866.xyz/https://raw.githubusercontent.com/oooldtoy/chinese_calender/main/festival.ics # URL with calendar events
                    name: 节假日 # required - name for these calendar events
                    color: teal # optional - defaults to pre-defined color for the service (zinc for ical)
                    params: # optional - additional params for the service
                      showName: true # optional - show name before event title in event line - defaults to false
    
    - Storage:
        - Kafka:
    #        href: https://kafka.acitrus.cn
            app: "kafka"
    #        podSelector: "app.kubernetes.io/instance=kafka"
            namespace: "default"
            name: Kafka
            # container: "kafka"
            description: kafka基础组件
            ping: https://kafka.acitrus.cn

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
            
  widgets.yaml: |
    #    - kubernetes:
    #        cluster:
    #          show: true
    #          cpu: true
    #          memory: true
    #          showLabel: true
    #          label: "cluster"
    #        nodes:
    #          show: true
    #          cpu: true
    #          memory: true
    #          showLabel: true
    # https://gethomepage.dev/widgets/info/search/
    - search:
        provider: google
        showSearchSuggestions: true
        target: _blank
        
    # - resources:
    #     label: container
    #     cputemp: true
    #     uptime: true
    #     units: metric
    #     backend: resources
    #     expanded: true
    #     cpu: true
    #     memory: true
    #     network: default
    
    # https://www.cnblogs.com/wangguishe/p/15261358.html
    # curl -L https://bit.ly/glances | /bin/bash
    # https://github.com/nicolargo/glances/issues/2021#issuecomment-1197831157
    - resources:
        network: default
        expanded: true
        # label: "-"
      
    - glances:
        url: http://100.88.88.10:61208
        # username: user # optional if auth enabled in Glances
        # password: pass # optional if auth enabled in Glances
        version: 3 # required only if running glances v4 or higher, defaults to 3
        cpu: true # optional, enabled by default, disable by setting to false
        mem: true # optional, enabled by default, disable by setting to false
        cputemp: true # disabled by default
        uptime: true # disabled by default
        disk: / # disabled by default, use mount point of disk(s) in glances. Can also be a list (see below)
        diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
        expanded: true # show the expanded view
        # label: "甲" # optional
        
    - glances:
        url: http://100.88.88.12:61208
        # username: user # optional if auth enabled in Glances
        # password: pass # optional if auth enabled in Glances
        version: 3 # required only if running glances v4 or higher, defaults to 3
        cpu: true # optional, enabled by default, disable by setting to false
        mem: true # optional, enabled by default, disable by setting to false
        cputemp: true # disabled by default
        uptime: true # disabled by default
        disk: / # disabled by default, use mount point of disk(s) in glances. Can also be a list (see below)
        diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
        expanded: true # show the expanded view
        # label: "乙" # optional
        

  docker.yaml: ""