postgresqlIngress:
  enabled: true
  host: postgresql.tcp.acitrus.cn
  entryPoints:
    - gravitation
  tls:
    store:
      name: default
      namespace: traefik

postgresql:
  auth:
    existingSecret: postgresql-auth
    secretKeys:
      adminPasswordKey: postgres-password
  primary:
    extraEnvVars:
      - name: TZ
        value: Asia/Shanghai
