postgresqlIngress:
  enabled: true
  host: postgresql.tcp.acitrus.cn
  entryPoints:
    - gravitation
  tls:
    domains:
      - main: acitrus.cn
        sans:
          - postgresql.tcp.acitrus.cn

postgresql:
  auth:
    existingSecret: postgresql-auth
    secretKeys:
      adminPasswordKey: postgres-password
  primary:
    extraEnvVars:
      - name: TZ
        value: Asia/Shanghai
